import {api,Content,ensureIdentity,newKey,go,message,today} from '../../lib/api';
Page({data:{packages:[] as Content[],slots:[] as any[],filteredSlots:[] as any[],packageId:'',packageName:'',group:false,loading:true,error:'',submitError:'',busy:false,minDate:today(),slotLabel:'不指定，人工沟通',form:{date:'',contactName:'',phone:'',adults:'',children:'',team:'',total:'',note:'',slotId:'',consent:false}},_key:newKey(),_fingerprint:'',
 onLoad(options:Record<string,string>){this.setData({packageId:options.id || '',group:options.group==='1'});},onShow(){this.load();},
 async load(){this.setData({loading:true,error:''});try{const [packages,slots]=await Promise.all([api<Content[]>('/api/public/content?kind=package'),api<any[]>('/api/public/slots')]);const pkg=packages.find(p=>p.id===this.data.packageId);this.setData({packages,slots:slots.map(s=>({...s,label:s.start+"—"+s.end})),packageName:pkg?.name || (this.data.group?'未指定，人工沟通':'请选择套餐')});this.filterSlots();}catch(e){this.setData({error:message(e)});}finally{this.setData({loading:false});}},retry(){this.load();},
 input(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value});},
 date(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({'form.date':e.detail.value,'form.slotId':'',slotLabel:'不指定，人工沟通'});this.filterSlots();},
 pickPackage(e:WechatMiniprogram.CustomEvent<{value:string}>){const p=this.data.packages[Number(e.detail.value)];this.setData({packageId:p.id,packageName:p.name,'form.slotId':'',slotLabel:'不指定，人工沟通'});this.filterSlots();},
 filterSlots(){const filteredSlots=this.data.slots.filter((s:any)=>s.date===this.data.form.date&&(!this.data.packageId||s.package_ids.includes(this.data.packageId)));this.setData({filteredSlots});if(this.data.form.slotId&&!filteredSlots.some((s:any)=>s.id===this.data.form.slotId))this.clearSlot();},
 slot(e:WechatMiniprogram.CustomEvent<{value:string}>){const s=this.data.filteredSlots[Number(e.detail.value)];this.setData({'form.slotId':s.id,slotLabel:s.start+'—'+s.end});},
 clearSlot(){this.setData({'form.slotId':'',slotLabel:'不指定，人工沟通'});},
 consent(e:WechatMiniprogram.CustomEvent<{value:string[]}>){this.setData({'form.consent':e.detail.value.includes('agree')});},privacy(){go('/pages/about/index?section=privacy');},
 async submit(){if(this.data.busy)return;this.setData({busy:true,submitError:''});try{await ensureIdentity();const f=this.data.form;const payload={...f,packageId:this.data.packageId || null,group:this.data.group,...(this.data.group?{total:Number(f.total)}:{adults:Number(f.adults),children:Number(f.children)})};const fingerprint=JSON.stringify(payload);if(this._fingerprint && this._fingerprint!==fingerprint)this._key=newKey();this._fingerprint=fingerprint;const result=await api<{id:string}>('/api/visitor/bookings',{method:'POST',data:payload,auth:true,key:this._key});wx.redirectTo({url:'/pages/record/index?kind=bookings&id='+result.id});}catch(e){this.setData({submitError:message(e)});}finally{this.setData({busy:false});}}
});
