import {api,Content,Enrollment,ensureIdentity,newKey,go,message,today} from '../../lib/api';
Page({data:{packages:[] as Content[],packageId:'',packageName:'',enrollmentId:'',activity:null as Enrollment|null,group:false,loading:true,error:'',submitError:'',busy:false,minDate:today(),form:{date:'',contactName:'',phone:'',adults:'',children:'',team:'',total:'',note:'',preferredTime:'',slotId:'',consent:false}},_key:newKey(),_fingerprint:'',
 onLoad(options:Record<string,string>){this.setData({packageId:options.id || '',enrollmentId:options.enrollmentId || '',group:!options.enrollmentId && options.group==='1'});},onShow(){this.load();},
 async load(){this.setData({loading:true,error:''});try{if(this.data.enrollmentId){const activity=await api<Enrollment>('/api/public/enrollments/'+encodeURIComponent(this.data.enrollmentId));this.setData({activity,packageId:activity.packageId,packageName:activity.packageName,'form.date':activity.date,'form.slotId':activity.id});return;}const packages=await api<Content[]>('/api/public/content?kind=package');const pkg=packages.find(p=>p.id===this.data.packageId);this.setData({packages,packageName:pkg?.name || (this.data.group?'未指定，人工沟通':'请选择套餐')});}catch(e){this.setData({error:message(e)});}finally{this.setData({loading:false});}},retry(){this.load();},
 input(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value});},
 date(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({'form.date':e.detail.value,'form.slotId':''});},
 pickPackage(e:WechatMiniprogram.CustomEvent<{value:string}>){const p=this.data.packages[Number(e.detail.value)];this.setData({packageId:p.id,packageName:p.name,'form.slotId':''});},
 consent(e:WechatMiniprogram.CustomEvent<{value:string[]}>){this.setData({'form.consent':e.detail.value.includes('agree')});},privacy(){go('/pages/about/index?section=privacy');},
 async submit(){if(this.data.busy)return;this.setData({busy:true,submitError:''});try{await ensureIdentity();const f=this.data.form;const payload={...f,...(this.data.enrollmentId?{enrollmentId:this.data.enrollmentId}:{}),packageId:this.data.packageId || null,group:this.data.group,...(this.data.group?{total:Number(f.total)}:{adults:Number(f.adults),children:Number(f.children)})};const fingerprint=JSON.stringify(payload);if(this._fingerprint && this._fingerprint!==fingerprint)this._key=newKey();this._fingerprint=fingerprint;const result=await api<{id:string}>('/api/visitor/bookings',{method:'POST',data:payload,auth:true,key:this._key});wx.redirectTo({url:'/pages/record/index?kind=bookings&id='+result.id});}catch(e){this.setData({submitError:message(e)});}finally{this.setData({busy:false});}}
});
