import React,{useRef,useState} from 'react';
import {post,put} from './api';
import {Field,Drawer,ErrorBox,Empty,useRemote,Loading,Icon} from './ui';
import {AdminIcon} from './AdminUI';
import './admin-phase-2b.css';
const roles={admin:'系统管理员',content:'内容维护',reception:'接待 / 客服'};
export default function Accounts() {
  const remote=useRemote('accounts');const [editing,setEditing]=useState(null);
  const triggerRef=useRef(null);
  return <section className="admin-management admin-accounts-page" onClickCapture={e=>{const button=e.target.closest('button[data-account-trigger]');if(button)triggerRef.current=button;}}><div className="admin-management-header"><div><h1>账号权限</h1><p>管理后台工作人员账号与访问权限</p></div><button data-account-trigger onClick={()=>setEditing({username:'',password:'',roles:['content'],active:true,canExport:false})}><AdminIcon name="plus" size={18}/>新增账号</button></div><p className="admin-management-note">每位工作人员使用独立账号；导出权限需单独授权。</p><ErrorBox error={remote.error}/><Loading loading={remote.loading}/><div className="admin-management-list-heading"><h2>工作人员</h2><span>{remote.loading?'正在读取':remote.error?'读取失败':`${remote.data?.length ?? 0} 个账号`}</span></div><div className="table-region" role="region" aria-label="工作人员账号列表，可横向滚动" tabIndex={0} aria-busy={remote.loading}>{!remote.loading && !remote.error && !remote.data?.length?<Empty>暂无工作人员账号</Empty>:<table><thead><tr><th>账号</th><th>角色</th><th>状态</th><th>名单导出</th><th>操作</th></tr></thead><tbody>{remote.data?.map(a=><tr key={a.id}><td><strong className="admin-account-name">{a.username}</strong></td><td>{a.roles.map(r=>roles[r]).join('、')}</td><td><span className={`status ${a.active?'account-active':'account-inactive'}`}>{a.active?'启用':'停用'}</span></td><td><span className={a.canExport?'admin-export-authorized':'muted'}>{a.canExport?'已授权':'未授权'}</span></td><td><button className="text-button" data-account-trigger={a.id} onClick={()=>setEditing(a)}>管理</button></td></tr>)}</tbody></table>}</div>{editing?<AccountEditor key={editing.id || 'new'} value={editing} returnFocusTo={triggerRef.current} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);remote.refresh();}}/>:null}</section>;
}
function AccountEditor({value,onClose,onSaved,returnFocusTo}) {
  const [form,setForm]=useState({...value,password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const update=(k,v)=>setForm(f=>({...f,[k]:v}));
  const submit=async e=>{e.preventDefault();setBusy(true);try{await (form.id?put(`accounts/${form.id}`,form):post('accounts',form));onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="admin-account-drawer"><Drawer title={form.id?'工作人员账号':'新增工作人员'} onClose={onClose} manageFocus returnFocusTo={returnFocusTo}><form className="admin-account-form" onSubmit={submit}><div className="admin-account-body"><section className="admin-account-section"><h3>基本信息</h3><ErrorBox error={error}/><Field label="账号名称"><input required disabled={!!form.id} pattern="[a-zA-Z0-9_-]{3,40}" value={form.username} onChange={e=>update('username',e.target.value)}/></Field><Field label={form.id?'重设密码（留空则保留）':'初始密码'} hint="至少12个字符；请通过公司批准的方式交付本人。"><input type="password" autoComplete="new-password" minLength={12} required={!form.id} value={form.password} onChange={e=>update('password',e.target.value)}/></Field></section><fieldset><legend>岗位权限</legend>{Object.entries(roles).map(([key,label])=><label className="check-row" key={key}><input type="checkbox" checked={form.roles.includes(key)} onChange={e=>update('roles',e.target.checked?[...form.roles,key]:form.roles.filter(r=>r!==key))}/>{label}</label>)}</fieldset><section className="admin-account-section"><h3>账号状态与导出</h3><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>update('active',e.target.checked)}/>启用账号</label><label className="check-row"><input type="checkbox" checked={form.canExport} onChange={e=>update('canExport',e.target.checked)}/>单独授权名单导出</label><p className="admin-account-warning">权限、密码或启用状态变更后，此账号已有会话将失效，需要重新登录。最后一个管理员不能被停用。</p></section></div><footer className="admin-account-footer"><button disabled={busy}>保存账号</button></footer></form></Drawer></div>;
}
export function Audit() {
  const remote=useRemote('audit');
  return <section className="admin-management admin-audit-page"><div className="admin-management-header"><div><h1>操作记录</h1><p>查看后台关键操作及审计记录</p></div></div><div className="admin-management-toolbar"><p>显示最近500条关键操作，记录操作者、时间和变更摘要。</p><button className="secondary" onClick={remote.refresh}><Icon name="refresh"/>刷新</button></div><ErrorBox error={remote.error}/><Loading loading={remote.loading}/><div className="admin-management-list-heading"><h2>关键操作</h2><span>{remote.loading?'正在读取':remote.error?'读取失败':`${remote.data?.length ?? 0} 条记录`}</span></div><div className="table-region" role="region" aria-label="操作记录列表，可横向滚动" tabIndex={0} aria-busy={remote.loading}>{!remote.loading && !remote.error && !remote.data?.length?<Empty>暂无操作记录</Empty>:<table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>对象</th><th>摘要</th></tr></thead><tbody>{remote.data?.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('zh-CN')}</td><td className="admin-audit-actor">{a.actor_name || a.actor}</td><td className="admin-audit-action">{a.action}</td><td className="mono">{a.object}</td><td><details><summary>查看</summary><pre>{JSON.stringify(a.detail,null,2)}</pre></details></td></tr>)}</tbody></table>}</div></section>;
}
