import React,{useState} from 'react';
import {api,post,put} from './api';
import {Drawer,Field,ErrorBox,Empty,Loading,useRemote} from './ui';
import {CONTENT_KINDS} from '../../shared/status.mjs';
const states={draft:'草稿',published:'已发布',archived:'已下架'};
export default function Content() {
  const [kind,setKind]=useState('product'),[q,setQ]=useState(''),[editing,setEditing]=useState(null),[error,setError]=useState('');
  const remote=useRemote(`content?${new URLSearchParams({kind,q})}`);
  const edit=async item=>{try{setEditing(await api(`content/${item.id}`));}catch(e){setError(e.message);}};
  return <><div className="tabs">{Object.entries(CONTENT_KINDS).map(([key,name])=><button key={key} className={kind===key?'active':''} onClick={()=>{setKind(key);setEditing(null);}}>{name}</button>)}</div><div className="toolbar"><input className="search-input" aria-label="搜索内容" placeholder="检索名称、编码或系列" value={q} onChange={e=>setQ(e.target.value)}/><button disabled={kind==='site' && !!remote.data?.length} onClick={()=>setEditing({kind,name:'',state:'draft',sort:0,isTest:true,...(kind==='product'?{category:'violin',priceMode:'inquiry',specs:[]}:{}),...(kind==='lesson'?{type:'article'}:{}),images:[]})}>新增内容</button><button className="secondary" onClick={remote.refresh}>刷新</button></div><ErrorBox error={error || remote.error}/><Loading loading={remote.loading}/><div className="table-region"><table><thead><tr><th>封面</th><th>名称 / 编码</th><th>分类</th><th>状态</th><th>排序</th><th>操作</th></tr></thead><tbody>{remote.data?.map(c=><tr key={c.id}><td>{c.images?.[0]?<img className="thumbnail" src={c.images[0].startsWith('/api/media/')?c.images[0].replace('/api/media/','/api/admin/media/')+'/file':c.images[0]} alt=""/>:<span className="muted">未设置</span>}</td><td>{c.name}<small>{c.code || c.id}</small></td><td>{c.category==='violin'?'提琴':c.category==='gift'?'文创':c.category || c.type || '—'}</td><td><span className={`status ${c.state}`}>{states[c.state]}</span></td><td>{c.sort}</td><td><button className="text-button" onClick={()=>edit(c)}>维护 / 预览</button></td></tr>)}</tbody></table>{!remote.loading && !remote.data?.length?<Empty>暂无内容，可新增草稿</Empty>:null}</div>{editing?<ContentEditor key={editing.id || `${kind}-new`} value={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);remote.refresh();}}/>:null}</>;
}
const textFields={
  site:[['heroTitle','首屏主标题'],['heroSubtitle','首屏第二行'],['intro','企业介绍'],['notice','公告'],['phone','已审核服务电话'],['address','已审核地址'],['privacy','隐私说明'],['serviceNote','服务说明']],
  product:[['code','产品编码'],['brand','品牌'],['series','系列 / 文创分类'],['description','介绍及材料说明'],['priceNote','价格说明']],
  package:[['code','套餐编码'],['description','套餐介绍'],['ageNote','原稿年龄说明'],['durationNote','原稿时长说明'],['itinerary','行程'],['included','费用包含'],['excluded','费用不含'],['materials','作品 / 材料数量说明'],['meetingPoint','集合地点'],['transfer','转场安排'],['bookingNote','预约说明'],['cancelNote','取消及改期说明']],
  lesson:[['category','教学分类'],['description','正文 / 简介'],['audience','适合对象'],['form','授课形式'],['place','授课地点'],['courseTime','公开时间说明'],['courseFee','公开费用说明'],['rights','内容授权说明']],
  spot:[['description','介绍'],['address','已核实地址'],['opening','开放说明'],['visitNote','到访 / 临时公告']]
};
const assets=['hero-violin.jpg','workshop.jpg','wenchuang.jpg','city.jpg','lake.jpg','industry.jpg','green.jpg','yorray-logo.png',...['c','i','g'].flatMap(k=>[1,2,3,4].map(n=>`${k}${n}.jpg`)),...['l1.jpg','l2.jpg','l3.jpg']];
function ContentEditor({value,onClose,onSaved}) {
  const [form,setForm]=useState(value),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const media=useRemote('media');const update=(k,v)=>setForm(f=>({...f,[k]:v}));
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try{
    const {id,kind,name,state,sort,version,...data}=form;
    if(kind==='product')data.specs=(form.specs || []).map(s=>({...s,...(s.price==null?{}:{price:Number(s.price)})}));
    const payload={kind,name,state,sort:Number(sort),version,data};
    await (id?put(`content/${id}`,payload):post('content',payload));onSaved();
  }catch(e){setError(e.message);}finally{setBusy(false);}};
  const imageOptions=[...assets.map(x=>({url:`/assets/${x}`,label:x})),...(media.data || []).filter(m=>m.mime.startsWith('image/')).map(m=>({url:`/api/media/${m.id}`,label:m.filename}))];
  return <Drawer title={`${CONTENT_KINDS[form.kind]} · 维护`} onClose={onClose}><form onSubmit={save}><ErrorBox error={error}/><Field label="名称"><input required maxLength={120} value={form.name} onChange={e=>update('name',e.target.value)}/></Field><div className="pair"><Field label="发布状态"><select value={form.state} onChange={e=>update('state',e.target.value)}>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="排序"><input type="number" min="0" max="10000" value={form.sort} onChange={e=>update('sort',e.target.value)}/></Field></div>
    {form.kind==='product'?<><Field label="产品类型"><select value={form.category} onChange={e=>update('category',e.target.value)}><option value="violin">提琴</option><option value="gift">文创</option></select></Field><Field label="价格展示"><select value={form.priceMode} onChange={e=>update('priceMode',e.target.value)}><option value="inquiry">咨询报价</option><option value="reference">参考价格</option></select></Field>{form.priceMode==='reference'?<Field label="测试参考价（元）"><input type="number" min="0" step="0.01" value={form.price??''} onChange={e=>update('price',Number(e.target.value))}/></Field>:null}<fieldset><legend>展示规格</legend><small>规格可以独立维护参数、参考价和图片；留空图库时沿用产品图片。</small>{(form.specs || []).map((spec,i)=><section className="history" key={i}><Field label="规格名称"><input value={spec.name} onChange={e=>update('specs',form.specs.map((s,n)=>n===i?{...s,name:e.target.value}:s))}/></Field><Field label="规格参数"><textarea value={spec.description} onChange={e=>update('specs',form.specs.map((s,n)=>n===i?{...s,description:e.target.value}:s))}/></Field><Field label="规格参考价（可留空）"><input type="number" min="0" step="0.01" value={spec.price??''} onChange={e=>update('specs',form.specs.map((s,n)=>n===i?{...s,price:e.target.value===''?null:Number(e.target.value)}:s))}/></Field>{(spec.images || []).map((img,j)=><div className="image-edit" key={j}><select aria-label="规格图片" value={img} onChange={e=>update('specs',form.specs.map((s,n)=>n===i?{...s,images:s.images.map((x,k)=>k===j?e.target.value:x)}:s))}>{imageOptions.map(x=><option key={x.url} value={x.url}>{x.label}</option>)}</select><button type="button" className="text-button" onClick={()=>update('specs',form.specs.map((s,n)=>n===i?{...s,images:s.images.filter((_,k)=>k!==j)}:s))}>移除规格图片</button></div>)}<button type="button" className="secondary" disabled={(spec.images?.length || 0)>=12} onClick={()=>update('specs',form.specs.map((s,n)=>n===i?{...s,images:[...(s.images || []),imageOptions[0].url]}:s))}>添加规格图片</button><button type="button" className="text-button" onClick={()=>update('specs',form.specs.filter((_,n)=>n!==i))}>移除此规格</button></section>)}<button type="button" className="secondary full" disabled={(form.specs?.length || 0)>=50} onClick={()=>update('specs',[...(form.specs || []),{name:'',description:'',images:[]}])}>新增展示规格</button></fieldset></>:null}
    {form.kind==='lesson'?<Field label="教学内容类型"><select value={form.type || 'article'} onChange={e=>update('type',e.target.value)}><option value="article">图文教学</option><option value="video">公开视频</option><option value="course">课程信息</option></select></Field>:null}
    {textFields[form.kind].map(([k,label])=><Field key={k} label={label}>{['description','intro','privacy','serviceNote','itinerary','bookingNote','cancelNote'].includes(k)?<textarea rows={k==='intro'?7:3} maxLength={12000} value={form[k] || ''} onChange={e=>update(k,e.target.value)}/>:<input maxLength={1500} value={form[k] || ''} onChange={e=>update(k,e.target.value)}/>}</Field>)}
    {form.kind==='package'?<><div className="pair"><Field label="原稿亲子参考价（元 / 组）"><input type="number" min="0" value={form.referenceParentPrice??''} onChange={e=>update('referenceParentPrice',Number(e.target.value))}/></Field><Field label="原稿单人参考价（元 / 张）"><input type="number" min="0" value={form.referenceSinglePrice??''} onChange={e=>update('referenceSinglePrice',Number(e.target.value))}/></Field></div><label className="check-row"><input type="checkbox" checked={!!form.highlight} onChange={e=>update('highlight',e.target.checked)}/>首页推荐</label><p className="muted">票型对象、优惠及作品数量待公司核定；此处维护参考信息，不自动计算预约费用。</p></>:null}
    {form.kind==='site'?<label className="check-row"><input type="checkbox" checked={!!form.bookingEnabled} onChange={e=>update('bookingEnabled',e.target.checked)}/>允许本地测试预约申请</label>:null}
    <fieldset><legend>内容图片</legend><small>保留原始素材；新图片先在“媒体上传”中上传。</small>{(form.images || []).map((image,i)=><div className="image-edit" key={i}><select value={image} onChange={e=>update('images',form.images.map((x,n)=>n===i?e.target.value:x))}>{imageOptions.map(x=><option key={x.url} value={x.url}>{x.label}</option>)}</select><button type="button" className="text-button" onClick={()=>update('images',form.images.filter((_,n)=>n!==i))}>移除</button></div>)}<button type="button" className="secondary full" disabled={(form.images?.length || 0)>=12} onClick={()=>update('images',[...(form.images || []),imageOptions[0].url])}>添加图片</button></fieldset>
    {form.kind==='lesson' && form.type==='video'?<><Field label="已上传视频"><select value={form.mediaId || ''} onChange={e=>update('mediaId',e.target.value)}><option value="">请选择视频文件</option>{media.data?.filter(m=>m.mime.startsWith('video/')).map(m=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></Field>{form.mediaId?<video className="media-preview" src={`/api/admin/media/${form.mediaId}/file`} controls preload="metadata" onLoadedMetadata={e=>{const n=e.currentTarget.duration;if(Number.isFinite(n) && n>0)update('duration',n);}} onError={()=>setError('视频预览失败，请核对文件编码或重新上传')}/>:null}<Field label="实际时长（秒）" hint="预览读取成功后自动填写；发布前请核对。"><input type="number" min="0.01" step="0.01" value={form.duration || ''} onChange={e=>update('duration',Number(e.target.value))}/></Field></>:null}
    {form.kind==='spot'?<fieldset><legend>地图位置（核实后填写）</legend><Field label="纬度"><input type="number" step="any" min="-90" max="90" value={form.latitude??''} onChange={e=>update('latitude',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="经度"><input type="number" step="any" min="-180" max="180" value={form.longitude??''} onChange={e=>update('longitude',e.target.value===''?null:Number(e.target.value))}/></Field><label className="check-row"><input type="checkbox" checked={!!form.coordinateVerified} onChange={e=>update('coordinateVerified',e.target.checked)}/>坐标已由工作人员核实</label><small>未核实坐标时不开放导航，不填猜测位置。</small></fieldset>:null}
    {form.images?.[0]?<img className="cover-preview" src={form.images[0].startsWith('/api/media/')?form.images[0].replace('/api/media/','/api/admin/media/')+'/file':form.images[0]} alt="封面预览"/>:null}<p className="muted">本地测试资料；草稿不会出现在小程序公开列表中。</p><button className="full" disabled={busy}>{busy?'保存中…':'保存内容'}</button></form></Drawer>;
}
