import React,{useState} from 'react';
import {ErrorBox,Empty,useRemote,Loading,Icon} from './ui';
import {AdminIcon} from './AdminUI';
import './admin-phase-2b.css';
const states={draft:'草稿',published:'已发布',archived:'已下架'};
export default function Media() {
  const remote=useRemote('media');const [preview,setPreview]=useState(null),[error,setError]=useState('');
  return <section className="admin-management admin-media-page"><div className="admin-management-header"><div><h1>素材库</h1><p>查看已上传的图片、视频及内容关联</p></div></div><div className="admin-management-toolbar"><p>图片和视频可在内容维护中直接上传。本页用于查找、预览与复用已有文件，上传文件不会自动发布。</p><button className="secondary" onClick={remote.refresh}><Icon name="refresh"/>刷新素材</button></div>
    {preview?<section className="admin-media-preview" aria-label="素材预览"><div className="admin-preview-heading"><h2>{preview.filename}</h2><button className="text-button" onClick={()=>{setPreview(null);setError('');}}>关闭预览</button></div>{preview.mime.startsWith('video/')?<video key={preview.id} className="media-preview" controls src={`/api/admin/media/${preview.id}/file`} onError={()=>setError('媒体预览失败，请核对文件格式或重新上传')}/>:<img className="cover-preview" src={`/api/admin/media/${preview.id}/file`} alt={preview.filename}/>}</section>:null}
    <ErrorBox error={error || remote.error}/><Loading loading={remote.loading}/><div className="admin-management-list-heading"><h2>已有素材</h2><span>{remote.loading?'正在读取':remote.error?'读取失败':`${remote.data?.length ?? 0} 个文件`}</span></div><div className="table-region" role="region" aria-label="素材列表，可横向滚动" tabIndex={0} aria-busy={remote.loading}>{!remote.loading && !remote.error && !remote.data?.length?<Empty>尚无文件，请在内容维护中上传</Empty>:<table><thead><tr><th>文件名</th><th>类型 / 大小</th><th>关联内容</th><th>上传时间</th><th>操作</th></tr></thead><tbody>{remote.data?.map(m=><tr key={m.id}><td><div className="admin-file-identity"><span className="admin-file-icon"><AdminIcon name={m.mime.startsWith('video/')?'lesson':'media'}/></span><strong className="admin-file-name" title={m.filename}>{m.filename}</strong></div></td><td>{m.mime}<small>{(m.size/1024/1024).toFixed(2)} MB</small></td><td>{m.usedBy?.length?m.usedBy.map(c=><div className="admin-media-reference" key={c.id}><span>{c.name}</span><span className={`status ${c.state}`}>{states[c.state]}</span></div>):<span className="muted">尚未关联</span>}</td><td>{new Date(m.created_at).toLocaleString('zh-CN')}</td><td><button className="text-button" data-media-key={m.id} onClick={()=>{setPreview(m);setError('');}}>预览</button></td></tr>)}</tbody></table>}</div></section>;
}
