import React,{useEffect,useRef,useState} from 'react';
import {api,post} from './api';
import {Field,ErrorBox,Empty,Drawer,Icon,useRemote,Status,Loading} from './ui';
import {AdminIcon} from './AdminUI';
import {BOOKING_STATES,CONSULTATION_STATES} from '../../shared/status.mjs';
import './admin-phase-2a.css';
export default function Operations({kind,user}) {
  const bookings=kind==='bookings', labels=bookings?BOOKING_STATES:CONSULTATION_STATES;
  const [q,setQ]=useState(''),[state,setState]=useState(''),[unassigned,setUnassigned]=useState(false),[joinOnly,setJoinOnly]=useState(false),[selected,setSelected]=useState(null),[error,setError]=useState('');
  const regionRef=useRef(null),triggerRef=useRef(null);
  const remote=useRemote(`${kind}?${new URLSearchParams({q,state,...(unassigned?{unassigned:'1'}:{}),...(bookings && joinOnly?{enrollment:'1'}:{})})}`), staff=useRemote('staff'),slots=useRemote('slots');
  const view=async row=>{try{setError('');setSelected(await api(`${kind}/${row.id}`));}catch(e){setError(e.message);}};
  const exportRows=async()=>{try{const r=await fetch(`/api/admin/export?kind=${kind}`);if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`${kind}.csv`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}};
  const close=()=>{const key=selected?.id;setSelected(null);queueMicrotask(()=>{const target=triggerRef.current?.isConnected?triggerRef.current:regionRef.current?.querySelector(`[data-detail-key="${CSS.escape(key || '')}"]`) || regionRef.current?.querySelector('.ops-search input');target?.focus();});};
  return <section ref={regionRef} className={`ops-page ops-records ${bookings?'ops-reservations':'ops-consultations'}`} onClickCapture={e=>{const button=e.target.closest('button[data-detail-key]');if(button)triggerRef.current=button;}}>
    <div className="ops-page-header"><div><h1>{bookings?'研学预约':'咨询管理'}</h1><p>{bookings?'查看游客研学申请，记录联系情况并安排接待':'查看内容与服务咨询，记录人工跟进及沟通结果'}</p></div></div>
    <div className="ops-toolbar"><div className="ops-filters"><div className="search ops-search"><Icon name="search"/><input aria-label="检索编号或联系人" placeholder="检索编号、联系人或活动名称" value={q} onChange={e=>setQ(e.target.value)}/></div><label className="inline ops-state-filter"><span>状态</span><select aria-label="状态筛选" value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="inline ops-check"><input type="checkbox" checked={unassigned} onChange={e=>setUnassigned(e.target.checked)}/>仅看未指派</label>{bookings?<label className="inline ops-check"><input type="checkbox" checked={joinOnly} onChange={e=>setJoinOnly(e.target.checked)}/>仅跟团报名</label>:null}</div><div className="ops-toolbar-actions"><button className="secondary" onClick={remote.refresh}><Icon name="refresh"/>刷新</button>{user.canExport?<button className="secondary" onClick={exportRows}>导出名单</button>:null}</div></div>
    <ErrorBox error={error || remote.error}/><Loading loading={remote.loading}/>
    <div className="ops-list-heading"><h2>{bookings?'预约记录':'咨询记录'}</h2><span>{remote.loading?'正在读取':remote.error?'读取失败':`${remote.data?.length ?? 0} 条${q || state || unassigned || (bookings && joinOnly)?'筛选结果':'记录'}`}</span></div>
    <div className={`table-region ${selected?'with-detail':''}`} tabIndex={0} role="region" aria-label={bookings?'研学预约列表，可横向滚动':'咨询列表，可横向滚动'} aria-busy={remote.loading}>
      {!remote.loading && !remote.error && !remote.data?.length?<Empty>{q || state || unassigned || (bookings && joinOnly)?'未找到符合条件的记录':bookings?'暂无预约；小程序提交后将显示在此处':'暂无咨询；小程序提交后将显示在此处'}</Empty>:<table><thead><tr><th>{bookings?'联系人 / 编号':'编号'}</th><th>{bookings?'套餐 / 团队':'关联内容 / 来源'}</th><th>{bookings?'意向日期':'联系人'}</th><th>{bookings?'人数':'提交时间'}</th><th>状态</th><th>负责人</th><th>操作</th></tr></thead><tbody>{remote.data?.map(row=><tr key={row.id} className={selected?.id===row.id?'selected':''}><td>{bookings?<strong className="ops-primary-value">{row.request.contactName}</strong>:null}<span className="mono ops-record-id">{row.id}</span></td><td>{row.request.enrollment?<><span className="ops-primary-value">跟团报名 · {row.request.enrollment.title}</span><small>{row.snapshot?.name}</small></>:<span className="ops-primary-value">{row.request.team || row.snapshot?.name || row.request.source}</span>}{!bookings?<small className="ops-message-summary">{row.request.message}</small>:null}</td><td>{bookings?row.request.date:row.request.contactName}</td><td>{bookings?<><strong className="ops-number">{row.headcount}</strong><small>{row.request.group?'团体':`成人${row.request.adults} / 儿童${row.request.children}`}</small></>:new Date(row.created_at).toLocaleDateString('zh-CN')}</td><td><Status state={row.state} labels={labels}/></td><td>{staff.data?.find(a=>a.id===row.assignee)?.username || '未指派'}</td><td><button className="text-button" data-detail-key={row.id} onClick={()=>view(row)}>查看</button></td></tr>)}</tbody></table>}
    </div><p className="footnote">{bookings?'申请提交不代表接待已确认；待确认申请不锁定场次容量。':'咨询记录用于人工跟进，不代表购买或课程报名。'}</p>
    {selected?<OperationDetail key={`${selected.id}-${selected.version}`} row={selected} kind={kind} staff={staff.data || []} slots={slots.data || []} returnFocusTo={triggerRef.current} onClose={close} onSaved={row=>{setSelected(row);remote.refresh();slots.refresh();}}/>:null}
  </section>;
}
function OperationDetail({row,kind,staff,slots,onClose,onSaved,returnFocusTo}) {
  const detailRef=useRef(null);
  useEffect(()=>{const root=detailRef.current;root?.querySelector('.icon-button')?.focus({preventScroll:true});const body=root?.querySelector('.ops-drawer-body');if(body)body.scrollTop=0;},[]);
  const bookings=kind==='bookings',labels=bookings?BOOKING_STATES:CONSULTATION_STATES;
  const [note,setNote]=useState(''),[slotId,setSlot]=useState(row.state==='pending'?row.request.enrollment?.id || '':''),[assignee,setAssignee]=useState(row.assignee || ''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(action,extra={})=>{setBusy(true);setError('');try{onSaved(await post(`${kind}/${row.id}`,{action,version:row.version,note,slotId,assignee,...extra}));}catch(e){setError(e.message);}finally{setBusy(false);}};
  const compatible=slots.filter(s=>!s.paused && (row.snapshot?.id==='group-general' || s.package_ids.includes(row.snapshot?.id)) && (row.state!=='pending' || !row.request.enrollment || s.id===row.request.enrollment.id));
  return <div className="ops-drawer" ref={detailRef}><Drawer title={bookings?'预约详情':'咨询详情'} onClose={onClose} manageFocus returnFocusTo={returnFocusTo}>
    <div className="ops-drawer-body">
      <section className="ops-detail-section"><h3>{bookings?'预约信息':'咨询对象'}</h3><dl className="detail-list"><dt>编号</dt><dd className="mono">{row.id}</dd><dt>{bookings?'套餐 / 团队':'关联内容'}</dt><dd>{row.request.team || row.snapshot?.name || '其他服务'}{row.snapshot?.spec?<small>规格：{row.snapshot.spec}</small>:null}</dd>{bookings?<><dt>意向日期</dt><dd>{row.request.date}</dd>{row.request.preferredTime?<><dt>意向时间段</dt><dd>{row.request.preferredTime}</dd></>:null}<dt>人数</dt><dd>{row.request.group?`${row.headcount}人（团体）`:`成人${row.request.adults} / 儿童${row.request.children}`}</dd></>:null}<dt>状态</dt><dd><Status state={row.state} labels={labels}/></dd></dl></section>
      <section className="ops-detail-section"><h3>联系信息</h3><dl className="detail-list"><dt>联系人</dt><dd>{row.request.contactName}</dd><dt>联系电话</dt><dd>{row.request.phone}</dd><dt>{bookings?'需求说明':'咨询内容'}</dt><dd className="pre-line">{row.request.note || row.request.message || '未填写'}</dd></dl></section>
      {row.request.enrollment?<div className="note-box"><h3>跟团报名 · 报名时活动信息</h3><p>{row.request.enrollment.title}</p><p>{row.request.enrollment.date} {row.request.enrollment.start}—{row.request.enrollment.end}</p><p>集合地点：{row.request.enrollment.meetingPoint}</p><small>待确认时仅可确认到游客所选场次；其他安排须先与游客沟通。</small></div>:null}
      {row.confirmed?<section className="ops-detail-section"><h3>已确认接待</h3><div className="note-box">已确认：{row.confirmed.date} {row.confirmed.start}—{row.confirmed.end}<br/>人数：{row.confirmed.total}<p>{row.confirmed.arrangement}</p>{row.arrived_at?<small>到访登记：{new Date(row.arrived_at).toLocaleString('zh-CN')}</small>:null}</div></section>:null}
      <section className="ops-detail-section ops-processing"><h3>{bookings?'接待处理':'咨询跟进'}</h3><ErrorBox error={error}/><Field label="接待 / 跟进负责人"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">未指派</option>{staff.map(s=><option key={s.id} value={s.id} disabled={!s.active || !s.canReceive}>{s.username}{!s.active?'（已停用）':!s.canReceive?'（不可接待）':''}</option>)}</select></Field><button className="secondary full" disabled={busy} onClick={()=>act('assign')}>保存指派</button>
        {bookings && (row.state==='pending' || row.changes?.some(c=>c.state==='pending' && c.type==='reschedule'))?<Field label="确认场次" hint="场次容量由后台明确建立；共用工坊和导师排班由工作人员核对。"><select value={slotId} onChange={e=>setSlot(e.target.value)}><option value="">请选择场次</option>{compatible.map(s=><option key={s.id} value={s.id}>{s.date} {s.start}—{s.end}（剩余{s.remaining}人）</option>)}</select></Field>:null}
        <Field label="联系与安排说明" hint="跟进备注供工作人员查看；确认、取消和结束结果会显示给游客。"><textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} maxLength={1500} placeholder="请记录联系情况、确认安排或处理原因"/></Field>
      </section>
      {row.changes?.map(c=><section className="history" key={c.id}><h3>变更申请 · {c.type==='cancel'?'取消':'日期 / 人数调整'}</h3><p>{c.data.reason}</p>{c.data.date?<p>意向：{c.data.date}，{c.data.total}人</p>:null}<small>{c.state==='pending'?'待处理':c.state==='approved'?'已批准':'未批准'} {c.result?.note}</small>{c.state==='pending'?<div className="action-grid"><button disabled={busy || (c.type==='reschedule'&&!slotId)} onClick={()=>act('change_approve',{changeId:c.id})}>批准变更</button><button className="secondary" disabled={busy} onClick={()=>act('change_reject',{changeId:c.id})}>不予变更</button></div>:null}</section>)}
      <section className="history"><h3>联系及操作记录</h3>{(row.contact_log || row.followups).map((l,i)=><p key={i}><small>{new Date(l.at).toLocaleString('zh-CN')} · {staff.find(s=>s.id===l.actor)?.username || '历史账号'}</small><br/>{l.note || ({assign:'指派负责人',arrive:'登记到访',complete:'完成接待',confirm:'确认接待',cancel:'人工取消',no_show:'登记未到访',change_approve:'批准变更',change_reject:'拒绝变更',followup:'登记跟进',reject:'无法接待',close:'结束咨询'}[l.action] || '业务操作')}</p>)}</section>
    </div>
    <footer className="ops-drawer-footer"><div className="action-grid"><button className={!bookings && row.state!=='closed'?'ops-primary':'secondary'} disabled={busy} onClick={()=>act('followup')}>登记跟进</button>{bookings && row.state==='pending'?<><button disabled={busy || !slotId || !compatible.some(s=>s.id===slotId)} onClick={()=>act('confirm')}>确认接待</button><button className="ops-danger" disabled={busy} onClick={()=>act('reject')}>无法接待</button></>:null}{bookings && row.state==='confirmed'?<><button className={row.arrived_at?'secondary':'ops-primary'} disabled={busy || !!row.arrived_at} onClick={()=>act('arrive')}>登记到访</button><button className={row.arrived_at?'ops-primary':'secondary'} disabled={busy || !row.arrived_at} onClick={()=>act('complete')}>完成接待</button><button className="secondary" disabled={busy || !!row.arrived_at} onClick={()=>act('no_show')}>登记未到访</button><button className="ops-danger" disabled={busy} onClick={()=>act('cancel')}>人工取消</button></>:null}{!bookings && row.state!=='closed'?<button className="ops-danger" disabled={busy} onClick={()=>act('close')}>结束咨询</button>:null}</div></footer>
  </Drawer></div>;
}
export function Slots() {
  const remote=useRemote('slots'), packages=useRemote('packages');
  const [editing,setEditing]=useState(null);
  const triggerRef=useRef(null);
  return <section className="ops-page ops-sessions" onClickCapture={e=>{const button=e.target.closest('button[data-slot-trigger]');if(button)triggerRef.current=button;}}>
    <div className="ops-page-header"><div><h1>场次管理</h1><p>管理接待日期、适用套餐、人数容量与研学报名发布</p></div><button data-slot-trigger onClick={()=>setEditing({date:'',start:'',end:'',capacity:'',external_count:0,package_ids:[],paused:false,note:'',enrollment:{state:'draft',title:'',packageId:'',description:'',meetingPoint:'',feeNote:'',registrationNote:''}})}><AdminIcon name="plus" size={18}/>新增场次</button></div>
    <div className="ops-toolbar"><p className="ops-toolbar-note">先维护日期、时段、套餐和实际人数，再发布跟团报名活动。</p><div className="ops-toolbar-actions"><button className="secondary" onClick={remote.refresh}><Icon name="refresh"/>刷新</button></div></div>
    <ErrorBox error={remote.error}/><Loading loading={remote.loading}/><div className="ops-list-heading"><h2>接待场次</h2><span>{remote.loading?'正在读取':remote.error?'读取失败':`${remote.data?.length ?? 0} 条记录`}</span></div>
    <div className="table-region" tabIndex={0} role="region" aria-label="接待场次列表，可横向滚动" aria-busy={remote.loading}>
      {!remote.loading && !remote.error && !remote.data?.length?<Empty>尚未配置场次，可先创建接待安排</Empty>:<table className="slots-table"><thead><tr><th>日期 / 活动</th><th>时段 / 套餐</th><th>人数上限</th><th>系统外人数</th><th>系统已确认</th><th>剩余名额</th><th>跟团发布</th><th>接待状态</th><th>操作</th></tr></thead><tbody>{remote.data?.map(s=><tr key={s.id}><td><strong className="ops-primary-value ops-date">{s.date}</strong><small>{s.enrollment.title || '未设置报名活动'}</small></td><td><span className="ops-primary-value ops-time">{s.start}—{s.end}</span><small>{s.package_ids.map(id=>packages.data?.find(p=>p.id===id)?.name || id).join('、')}</small></td><td className="ops-number">{s.capacity}</td><td className="ops-number">{s.external_count}</td><td className="ops-number">{s.confirmed_count}</td><td className="ops-number">{s.remaining}</td><td><span className={`status ${s.enrollment.state}`}>{{draft:'未发布',published:'已发布',archived:'已下架'}[s.enrollment.state]}</span></td><td><span className={`status ${s.paused?'ops-neutral':s.remaining>0?'ops-success':'ops-warning'}`}>{s.paused?'已暂停':s.remaining>0?'可申请':'已满员'}</span></td><td><button className="text-button" data-slot-trigger onClick={()=>setEditing(s)}>编辑 / 发布</button></td></tr>)}</tbody></table>}
    </div>
    <details className="ops-guide"><summary>接待场次与研学报名说明</summary><p>普通场次用于预约接待安排。已成团的场次可填写活动信息并发布，游客从小程序“研学 → 研学报名”选择活动申请跟团。系统外已成团人数与系统已确认人数共同计入人数上限；待确认申请不占名额，工作人员确认时重新检查容量。</p></details>
    {editing?<SlotEditor key={editing.id || 'new'} value={editing} packages={packages.data || []} returnFocusTo={triggerRef.current} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);remote.refresh();}}/>:null}
  </section>;
}
function SlotEditor({value,packages,onClose,onSaved,returnFocusTo}) {
  const [form,setForm]=useState({...value,enrollment:{state:'draft',...value.enrollment}}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const change=(key,val)=>setForm(f=>({...f,[key]:val}));
  const changeActivity=(key,val)=>setForm(f=>({...f,enrollment:{...f.enrollment,[key]:val}}));
  const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const data={...form,capacity:Number(form.capacity),externalCount:Number(form.external_count),packageIds:form.package_ids};await (form.id?api(`slots/${form.id}`,{method:'PUT',body:JSON.stringify(data)}):post('slots',data));onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const eligible=packages.filter(p=>form.package_ids.includes(p.id));
  const occupied=Number(form.external_count)+(value.confirmed_count || 0);
  return <div className="ops-drawer"><Drawer title="场次与研学报名配置" onClose={onClose} closeDisabled={busy} manageFocus returnFocusTo={returnFocusTo}><form className="ops-slot-form" onSubmit={save}><div className="ops-drawer-body">
    <section className="ops-detail-section"><h3>接待安排</h3><ErrorBox error={error}/><Field label="接待日期"><input type="date" required value={form.date} onInput={e=>change('date',e.currentTarget.value)} onChange={e=>change('date',e.target.value)}/></Field><div className="pair"><Field label="开始时间"><input type="time" required value={form.start} onInput={e=>change('start',e.currentTarget.value)} onChange={e=>change('start',e.target.value)}/></Field><Field label="结束时间"><input type="time" required value={form.end} onInput={e=>change('end',e.currentTarget.value)} onChange={e=>change('end',e.target.value)}/></Field></div>
    <div className="pair"><Field label="场次总人数上限" hint="包含已成团人员及新增跟团人员；成人和儿童均计入人数。"><input type="number" min="1" max="10000" required value={form.capacity} onChange={e=>change('capacity',e.target.value)}/></Field>
    <Field label="系统外已成团人数" hint="仅填写未通过本系统确认的实际人数；已录入系统并确认的人员不要重复计数，没有则填0。"><input type="number" min="0" max="10000" required value={form.external_count} onChange={e=>change('external_count',e.target.value)}/></Field></div>
    <p className="ops-capacity-note">系统已确认 {value.confirmed_count || 0} 人；合计已占用 {occupied} 人；剩余 {Math.max(0,Number(form.capacity)-occupied)} 人。待确认申请不计入已占用人数。</p>
    <fieldset><legend>适用套餐</legend>{packages.map(p=><label className="check-row" key={p.id}><input type="checkbox" checked={form.package_ids.includes(p.id)} onChange={e=>setForm(f=>({...f,package_ids:e.target.checked?[...f.package_ids,p.id]:f.package_ids.filter(id=>id!==p.id),enrollment:!e.target.checked && f.enrollment.packageId===p.id?{...f.enrollment,packageId:''}:f.enrollment}))}/>{p.name}</label>)}</fieldset>
    <Field label="内部接待说明" hint="仅供工作人员查看；游客看到下方填写的活动与报名说明。"><textarea maxLength={1500} value={form.note} onChange={e=>change('note',e.target.value)}/></Field></section>
    <fieldset><legend>研学报名发布</legend>
      <Field label="报名发布状态"><select value={form.enrollment.state} onChange={e=>changeActivity('state',e.target.value)}><option value="draft">未发布</option><option value="published">发布到小程序研学报名</option><option value="archived">下架报名活动</option></select></Field>
      <Field label="活动名称"><input maxLength={120} required={form.enrollment.state==='published'} value={form.enrollment.title || ''} onChange={e=>changeActivity('title',e.target.value)}/></Field>
      <Field label="跟团套餐" hint="从本场次适用套餐中选择一个已发布套餐，游客报名时自动带入。"><select required={form.enrollment.state==='published'} value={form.enrollment.packageId || ''} onChange={e=>changeActivity('packageId',e.target.value)}><option value="">请选择套餐</option>{eligible.map(p=><option key={p.id} value={p.id} disabled={p.state!=='published'}>{p.name}{p.state!=='published'?'（未发布）':''}</option>)}</select></Field>
      <Field label="活动介绍" hint="展示给游客；留空时沿用套餐介绍。"><textarea maxLength={5000} value={form.enrollment.description || ''} onChange={e=>changeActivity('description',e.target.value)}/></Field>
      <Field label="集合地点"><input maxLength={300} required={form.enrollment.state==='published'} value={form.enrollment.meetingPoint || ''} onChange={e=>changeActivity('meetingPoint',e.target.value)}/></Field>
      <Field label="公开费用说明" hint="填写已核实说明；留空显示咨询工作人员，不自动计算费用或优惠。"><textarea maxLength={500} value={form.enrollment.feeNote || ''} onChange={e=>changeActivity('feeNote',e.target.value)}/></Field>
      <Field label="公开报名说明"><textarea maxLength={1500} value={form.enrollment.registrationNote || ''} onChange={e=>changeActivity('registrationNote',e.target.value)}/></Field>
      <small>发布的是已经成团的活动。报名提交后仍待人工确认；下架停止新增跟团申请，已有报名记录保留。若修改已有报名的日期或套餐，请建立新场次。</small>
    </fieldset>
    <label className="check-row"><input type="checkbox" checked={!!form.paused} onChange={e=>change('paused',e.target.checked)}/>暂停此场次申请及新确认</label>
  </div><footer className="ops-drawer-footer"><button className="full" disabled={busy}>{busy?'保存中…':form.enrollment.state==='published'?'保存并发布':'保存场次'}</button></footer></form></Drawer></div>;
}
