import React,{useState} from 'react';
import {api,post} from './api';
import {Field,ErrorBox,Empty,Drawer,Icon,useRemote,Status,Loading} from './ui';
import {BOOKING_STATES,CONSULTATION_STATES} from '../../shared/status.mjs';
export default function Operations({kind,user}) {
  const bookings=kind==='bookings', labels=bookings?BOOKING_STATES:CONSULTATION_STATES;
  const [q,setQ]=useState(''),[state,setState]=useState(''),[unassigned,setUnassigned]=useState(false),[selected,setSelected]=useState(null),[error,setError]=useState('');
  const remote=useRemote(`${kind}?${new URLSearchParams({q,state,...(unassigned?{unassigned:'1'}:{})})}`), staff=useRemote('staff'),slots=useRemote('slots');
  const view=async row=>{try{setError('');setSelected(await api(`${kind}/${row.id}`));}catch(e){setError(e.message);}};
  const exportRows=async()=>{try{const r=await fetch(`/api/admin/export?kind=${kind}`);if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`${kind}.csv`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}};
  return <><div className="toolbar"><div className="search"><Icon name="search"/><input aria-label="检索编号或联系人" placeholder="请输入编号或联系人" value={q} onChange={e=>setQ(e.target.value)}/></div><label className="inline">状态<select aria-label="状态筛选" value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="inline"><input type="checkbox" checked={unassigned} onChange={e=>setUnassigned(e.target.checked)}/>仅看未指派</label><button className="secondary" onClick={remote.refresh}><Icon name="refresh"/>刷新</button>{user.canExport?<button className="secondary" onClick={exportRows}>导出名单</button>:null}</div>
    <ErrorBox error={error || remote.error}/><Loading loading={remote.loading}/><div className={`table-region ${selected?'with-detail':''}`}><table><thead><tr><th>编号</th><th>{bookings?'套餐 / 团队':'关联内容 / 来源'}</th><th>{bookings?'意向日期':'联系人'}</th><th>{bookings?'人数':'提交时间'}</th><th>状态</th><th>负责人</th><th>操作</th></tr></thead><tbody>{remote.data?.map(row=><tr key={row.id} className={selected?.id===row.id?'selected':''}><td className="mono">{row.id}</td><td>{row.request.team || row.snapshot?.name || row.request.source}</td><td>{bookings?row.request.date:row.request.contactName}</td><td>{bookings?row.headcount:new Date(row.created_at).toLocaleDateString('zh-CN')}</td><td><Status state={row.state} labels={labels}/></td><td>{staff.data?.find(a=>a.id===row.assignee)?.username || '未指派'}</td><td><button className="text-button" onClick={()=>view(row)}>查看</button></td></tr>)}</tbody></table>{!remote.loading && !remote.data?.length?<Empty>{q || state || unassigned?'没有符合条件的记录':'暂无记录；小程序提交后将显示在此处'}</Empty>:null}</div><p className="footnote">{bookings?'申请提交不代表接待已确认；待确认申请不锁定场次容量。':'咨询记录用于人工跟进，不代表购买或课程报名。'}</p>
    {selected?<OperationDetail key={`${selected.id}-${selected.version}`} row={selected} kind={kind} staff={staff.data || []} slots={slots.data || []} onClose={()=>setSelected(null)} onSaved={row=>{setSelected(row);remote.refresh();slots.refresh();}}/>:null}</>;
}
function OperationDetail({row,kind,staff,slots,onClose,onSaved}) {
  const bookings=kind==='bookings',labels=bookings?BOOKING_STATES:CONSULTATION_STATES;
  const [note,setNote]=useState(''),[slotId,setSlot]=useState(''),[assignee,setAssignee]=useState(row.assignee || ''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(action,extra={})=>{setBusy(true);setError('');try{onSaved(await post(`${kind}/${row.id}`,{action,version:row.version,note,slotId,assignee,...extra}));}catch(e){setError(e.message);}finally{setBusy(false);}};
  const compatible=slots.filter(s=>!s.paused && (row.snapshot?.id==='group-general' || s.package_ids.includes(row.snapshot?.id)));
  return <Drawer title={bookings?'预约详情':'咨询详情'} onClose={onClose}><dl className="detail-list"><dt>编号</dt><dd className="mono">{row.id}</dd><dt>{bookings?'套餐 / 团队':'关联内容'}</dt><dd>{row.request.team || row.snapshot?.name || '其他服务'}{row.snapshot?.spec?<small>规格：{row.snapshot.spec}</small>:null}</dd>{bookings?<><dt>意向日期</dt><dd>{row.request.date}</dd><dt>人数</dt><dd>{row.request.group?`${row.headcount}人（团体）`:`成人${row.request.adults} / 儿童${row.request.children}`}</dd></>:null}<dt>状态</dt><dd><Status state={row.state} labels={labels}/></dd><dt>联系人</dt><dd>{row.request.contactName}</dd><dt>联系电话</dt><dd>{row.request.phone}</dd><dt>{bookings?'需求说明':'咨询内容'}</dt><dd className="pre-line">{row.request.note || row.request.message || '未填写'}</dd></dl>
    {row.confirmed?<div className="note-box">已确认：{row.confirmed.date} {row.confirmed.start}—{row.confirmed.end}<br/>人数：{row.confirmed.total}<p>{row.confirmed.arrangement}</p>{row.arrived_at?<small>到访登记：{new Date(row.arrived_at).toLocaleString('zh-CN')}</small>:null}</div>:null}
    <ErrorBox error={error}/><Field label="接待 / 跟进负责人"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">未指派</option>{staff.map(s=><option key={s.id} value={s.id} disabled={!s.active || !s.canReceive}>{s.username}{!s.active?'（已停用）':!s.canReceive?'（不可接待）':''}</option>)}</select></Field><button className="secondary full" disabled={busy} onClick={()=>act('assign')}>保存指派</button>
    {bookings && (row.state==='pending' || row.changes?.some(c=>c.state==='pending' && c.type==='reschedule'))?<Field label="确认场次" hint="场次容量由后台明确建立；共用工坊和导师排班由工作人员核对。"><select value={slotId} onChange={e=>setSlot(e.target.value)}><option value="">请选择场次</option>{compatible.map(s=><option key={s.id} value={s.id}>{s.date} {s.start}—{s.end}（剩余{s.remaining}人）</option>)}</select></Field>:null}
    <Field label="联系与安排说明" hint="跟进备注供工作人员查看；确认、取消和结束结果会显示给游客。"><textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} maxLength={1500} placeholder="请记录联系情况、确认安排或处理原因"/></Field><div className="action-grid"><button className="secondary" disabled={busy} onClick={()=>act('followup')}>登记跟进</button>{bookings && row.state==='pending'?<><button disabled={busy || !slotId} onClick={()=>act('confirm')}>确认接待</button><button className="secondary" disabled={busy} onClick={()=>act('reject')}>无法接待</button></>:null}{bookings && row.state==='confirmed'?<><button disabled={busy || !!row.arrived_at} onClick={()=>act('arrive')}>登记到访</button><button disabled={busy || !row.arrived_at} onClick={()=>act('complete')}>完成接待</button><button className="secondary" disabled={busy || !!row.arrived_at} onClick={()=>act('no_show')}>登记未到访</button><button className="secondary" disabled={busy} onClick={()=>act('cancel')}>人工取消</button></>:null}{!bookings && row.state!=='closed'?<button disabled={busy} onClick={()=>act('close')}>结束咨询</button>:null}</div>
    {row.changes?.map(c=><section className="history" key={c.id}><h3>变更申请 · {c.type==='cancel'?'取消':'日期 / 人数调整'}</h3><p>{c.data.reason}</p>{c.data.date?<p>意向：{c.data.date}，{c.data.total}人</p>:null}<small>{c.state==='pending'?'待处理':c.state==='approved'?'已批准':'未批准'} {c.result?.note}</small>{c.state==='pending'?<div className="action-grid"><button disabled={busy || (c.type==='reschedule'&&!slotId)} onClick={()=>act('change_approve',{changeId:c.id})}>批准变更</button><button className="secondary" disabled={busy} onClick={()=>act('change_reject',{changeId:c.id})}>不予变更</button></div>:null}</section>)}
    <section className="history"><h3>联系及操作记录</h3>{(row.contact_log || row.followups).map((l,i)=><p key={i}><small>{new Date(l.at).toLocaleString('zh-CN')} · {staff.find(s=>s.id===l.actor)?.username || '历史账号'}</small><br/>{l.note || ({assign:'指派负责人',arrive:'登记到访',complete:'完成接待',confirm:'确认接待',cancel:'人工取消',no_show:'登记未到访',change_approve:'批准变更',change_reject:'拒绝变更',followup:'登记跟进',reject:'无法接待',close:'结束咨询'}[l.action] || '业务操作')}</p>)}</section></Drawer>;
}
export function Slots() {
  const remote=useRemote('slots'), packages=useRemote('packages');
  const [editing,setEditing]=useState(null),[error,setError]=useState('');
  return <><div className="note-box"><h3>场次与预约如何衔接</h3><p>场次是某一天、某个时段的接待安排。保存并开放后，小程序会按游客选择的日期和套餐显示可申请的意向时段；暂停或日期已过的场次不再提供选择。游客提交后仍为“待确认”，不占用人数上限；工作人员在研学预约中选择场次并确认后才计入已确认人数。没有配置时段时，游客仍可提交意向日期，由工作人员联系安排。</p></div><div className="toolbar"><p>每个场次需明确接待日期、时段、适用套餐和人数上限。</p><button onClick={()=>setEditing({date:'',start:'',end:'',capacity:'',package_ids:[],paused:false,note:''})}>新增场次</button><button className="secondary" onClick={remote.refresh}>刷新</button></div><ErrorBox error={remote.error || error}/><Loading loading={remote.loading}/><div className="table-region"><table><thead><tr><th>日期</th><th>时段</th><th>人数上限</th><th>已确认人数</th><th>状态</th><th>操作</th></tr></thead><tbody>{remote.data?.map(s=><tr key={s.id}><td>{s.date}</td><td>{s.start}—{s.end}</td><td>{s.capacity}</td><td>{s.confirmed_count}</td><td>{s.paused?'已暂停':'可申请'}</td><td><button className="text-button" onClick={()=>setEditing(s)}>编辑</button></td></tr>)}</tbody></table>{!remote.data?.length?<Empty>尚未配置场次，可先创建接待安排</Empty>:null}</div>{editing?<SlotEditor key={editing.id || 'new'} value={editing} packages={packages.data || []} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);remote.refresh();}}/>:null}</>;
}
function SlotEditor({value,packages,onClose,onSaved}) {
  const [form,setForm]=useState(value),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const change=(key,val)=>setForm(f=>({...f,[key]:val}));
  const save=async e=>{e.preventDefault();setBusy(true);try{const data={...form,capacity:Number(form.capacity),packageIds:form.package_ids};await (form.id?api(`slots/${form.id}`,{method:'PUT',body:JSON.stringify(data)}):post('slots',data));onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <Drawer title="接待场次配置" onClose={onClose}><form onSubmit={save}><ErrorBox error={error}/><Field label="接待日期"><input type="date" required value={form.date} onChange={e=>change('date',e.target.value)}/></Field><div className="pair"><Field label="开始时间"><input type="time" required value={form.start} onChange={e=>change('start',e.target.value)}/></Field><Field label="结束时间"><input type="time" required value={form.end} onChange={e=>change('end',e.target.value)}/></Field></div><Field label="人数上限" hint="请按实际接待能力填写；成人和儿童均计入人数。"><input type="number" min="1" max="10000" required value={form.capacity} onChange={e=>change('capacity',e.target.value)}/></Field><fieldset><legend>适用套餐</legend>{packages.map(p=><label className="check-row" key={p.id}><input type="checkbox" checked={form.package_ids.includes(p.id)} onChange={e=>change('package_ids',e.target.checked?[...form.package_ids,p.id]:form.package_ids.filter(id=>id!==p.id))}/>{p.name}</label>)}</fieldset><Field label="接待说明"><textarea value={form.note} onChange={e=>change('note',e.target.value)}/></Field><label className="check-row"><input type="checkbox" checked={!!form.paused} onChange={e=>change('paused',e.target.checked)}/>暂停此场次申请</label><button className="full" disabled={busy}>{busy?'保存中…':'保存场次'}</button></form></Drawer>;
}
