import React,{useState} from 'react';
import {api,post} from './api';
import {Field,ErrorBox,Empty,Drawer,Icon,useRemote,Status,Loading} from './ui';
import {BOOKING_STATES,CONSULTATION_STATES} from '../../shared/status.mjs';
export default function Operations({kind,user}) {
  const bookings=kind==='bookings', labels=bookings?BOOKING_STATES:CONSULTATION_STATES;
  const [q,setQ]=useState(''),[state,setState]=useState(''),[unassigned,setUnassigned]=useState(false),[joinOnly,setJoinOnly]=useState(false),[selected,setSelected]=useState(null),[error,setError]=useState('');
  const remote=useRemote(`${kind}?${new URLSearchParams({q,state,...(unassigned?{unassigned:'1'}:{}),...(bookings && joinOnly?{enrollment:'1'}:{})})}`), staff=useRemote('staff'),slots=useRemote('slots');
  const view=async row=>{try{setError('');setSelected(await api(`${kind}/${row.id}`));}catch(e){setError(e.message);}};
  const exportRows=async()=>{try{const r=await fetch(`/api/admin/export?kind=${kind}`);if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`${kind}.csv`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}};
  return <><div className="toolbar"><div className="search"><Icon name="search"/><input aria-label="检索编号或联系人" placeholder="检索编号、联系人或活动名称" value={q} onChange={e=>setQ(e.target.value)}/></div><label className="inline">状态<select aria-label="状态筛选" value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="inline"><input type="checkbox" checked={unassigned} onChange={e=>setUnassigned(e.target.checked)}/>仅看未指派</label>{bookings?<label className="inline"><input type="checkbox" checked={joinOnly} onChange={e=>setJoinOnly(e.target.checked)}/>仅跟团报名</label>:null}<button className="secondary" onClick={remote.refresh}><Icon name="refresh"/>刷新</button>{user.canExport?<button className="secondary" onClick={exportRows}>导出名单</button>:null}</div>
    <ErrorBox error={error || remote.error}/><Loading loading={remote.loading}/><div className={`table-region ${selected?'with-detail':''}`}><table><thead><tr><th>编号</th><th>{bookings?'套餐 / 团队':'关联内容 / 来源'}</th><th>{bookings?'意向日期':'联系人'}</th><th>{bookings?'人数':'提交时间'}</th><th>状态</th><th>负责人</th><th>操作</th></tr></thead><tbody>{remote.data?.map(row=><tr key={row.id} className={selected?.id===row.id?'selected':''}><td className="mono">{row.id}</td><td>{row.request.enrollment?<><span>跟团报名 · {row.request.enrollment.title}</span><small>{row.snapshot?.name}</small></>:row.request.team || row.snapshot?.name || row.request.source}</td><td>{bookings?row.request.date:row.request.contactName}</td><td>{bookings?row.headcount:new Date(row.created_at).toLocaleDateString('zh-CN')}</td><td><Status state={row.state} labels={labels}/></td><td>{staff.data?.find(a=>a.id===row.assignee)?.username || '未指派'}</td><td><button className="text-button" onClick={()=>view(row)}>查看</button></td></tr>)}</tbody></table>{!remote.loading && !remote.data?.length?<Empty>{q || state || unassigned?'没有符合条件的记录':'暂无记录；小程序提交后将显示在此处'}</Empty>:null}</div><p className="footnote">{bookings?'申请提交不代表接待已确认；待确认申请不锁定场次容量。':'咨询记录用于人工跟进，不代表购买或课程报名。'}</p>
    {selected?<OperationDetail key={`${selected.id}-${selected.version}`} row={selected} kind={kind} staff={staff.data || []} slots={slots.data || []} onClose={()=>setSelected(null)} onSaved={row=>{setSelected(row);remote.refresh();slots.refresh();}}/>:null}</>;
}
function OperationDetail({row,kind,staff,slots,onClose,onSaved}) {
  const bookings=kind==='bookings',labels=bookings?BOOKING_STATES:CONSULTATION_STATES;
  const [note,setNote]=useState(''),[slotId,setSlot]=useState(row.state==='pending'?row.request.enrollment?.id || '':''),[assignee,setAssignee]=useState(row.assignee || ''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const act=async(action,extra={})=>{setBusy(true);setError('');try{onSaved(await post(`${kind}/${row.id}`,{action,version:row.version,note,slotId,assignee,...extra}));}catch(e){setError(e.message);}finally{setBusy(false);}};
  const compatible=slots.filter(s=>!s.paused && (row.snapshot?.id==='group-general' || s.package_ids.includes(row.snapshot?.id)) && (row.state!=='pending' || !row.request.enrollment || s.id===row.request.enrollment.id));
  return <Drawer title={bookings?'预约详情':'咨询详情'} onClose={onClose}><dl className="detail-list"><dt>编号</dt><dd className="mono">{row.id}</dd><dt>{bookings?'套餐 / 团队':'关联内容'}</dt><dd>{row.request.team || row.snapshot?.name || '其他服务'}{row.snapshot?.spec?<small>规格：{row.snapshot.spec}</small>:null}</dd>{bookings?<><dt>意向日期</dt><dd>{row.request.date}</dd><dt>人数</dt><dd>{row.request.group?`${row.headcount}人（团体）`:`成人${row.request.adults} / 儿童${row.request.children}`}</dd></>:null}<dt>状态</dt><dd><Status state={row.state} labels={labels}/></dd><dt>联系人</dt><dd>{row.request.contactName}</dd><dt>联系电话</dt><dd>{row.request.phone}</dd><dt>{bookings?'需求说明':'咨询内容'}</dt><dd className="pre-line">{row.request.note || row.request.message || '未填写'}</dd></dl>
    {row.request.enrollment?<div className="note-box"><h3>跟团报名 · 报名时活动信息</h3><p>{row.request.enrollment.title}</p><p>{row.request.enrollment.date} {row.request.enrollment.start}—{row.request.enrollment.end}</p><p>集合地点：{row.request.enrollment.meetingPoint}</p><small>待确认时仅可确认到游客所选场次；其他安排须先与游客沟通。</small></div>:null}
    {row.confirmed?<div className="note-box">已确认：{row.confirmed.date} {row.confirmed.start}—{row.confirmed.end}<br/>人数：{row.confirmed.total}<p>{row.confirmed.arrangement}</p>{row.arrived_at?<small>到访登记：{new Date(row.arrived_at).toLocaleString('zh-CN')}</small>:null}</div>:null}
    <ErrorBox error={error}/><Field label="接待 / 跟进负责人"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">未指派</option>{staff.map(s=><option key={s.id} value={s.id} disabled={!s.active || !s.canReceive}>{s.username}{!s.active?'（已停用）':!s.canReceive?'（不可接待）':''}</option>)}</select></Field><button className="secondary full" disabled={busy} onClick={()=>act('assign')}>保存指派</button>
    {bookings && (row.state==='pending' || row.changes?.some(c=>c.state==='pending' && c.type==='reschedule'))?<Field label="确认场次" hint="场次容量由后台明确建立；共用工坊和导师排班由工作人员核对。"><select value={slotId} onChange={e=>setSlot(e.target.value)}><option value="">请选择场次</option>{compatible.map(s=><option key={s.id} value={s.id}>{s.date} {s.start}—{s.end}（剩余{s.remaining}人）</option>)}</select></Field>:null}
    <Field label="联系与安排说明" hint="跟进备注供工作人员查看；确认、取消和结束结果会显示给游客。"><textarea rows={5} value={note} onChange={e=>setNote(e.target.value)} maxLength={1500} placeholder="请记录联系情况、确认安排或处理原因"/></Field><div className="action-grid"><button className="secondary" disabled={busy} onClick={()=>act('followup')}>登记跟进</button>{bookings && row.state==='pending'?<><button disabled={busy || !slotId || !compatible.some(s=>s.id===slotId)} onClick={()=>act('confirm')}>确认接待</button><button className="secondary" disabled={busy} onClick={()=>act('reject')}>无法接待</button></>:null}{bookings && row.state==='confirmed'?<><button disabled={busy || !!row.arrived_at} onClick={()=>act('arrive')}>登记到访</button><button disabled={busy || !row.arrived_at} onClick={()=>act('complete')}>完成接待</button><button className="secondary" disabled={busy || !!row.arrived_at} onClick={()=>act('no_show')}>登记未到访</button><button className="secondary" disabled={busy} onClick={()=>act('cancel')}>人工取消</button></>:null}{!bookings && row.state!=='closed'?<button disabled={busy} onClick={()=>act('close')}>结束咨询</button>:null}</div>
    {row.changes?.map(c=><section className="history" key={c.id}><h3>变更申请 · {c.type==='cancel'?'取消':'日期 / 人数调整'}</h3><p>{c.data.reason}</p>{c.data.date?<p>意向：{c.data.date}，{c.data.total}人</p>:null}<small>{c.state==='pending'?'待处理':c.state==='approved'?'已批准':'未批准'} {c.result?.note}</small>{c.state==='pending'?<div className="action-grid"><button disabled={busy || (c.type==='reschedule'&&!slotId)} onClick={()=>act('change_approve',{changeId:c.id})}>批准变更</button><button className="secondary" disabled={busy} onClick={()=>act('change_reject',{changeId:c.id})}>不予变更</button></div>:null}</section>)}
    <section className="history"><h3>联系及操作记录</h3>{(row.contact_log || row.followups).map((l,i)=><p key={i}><small>{new Date(l.at).toLocaleString('zh-CN')} · {staff.find(s=>s.id===l.actor)?.username || '历史账号'}</small><br/>{l.note || ({assign:'指派负责人',arrive:'登记到访',complete:'完成接待',confirm:'确认接待',cancel:'人工取消',no_show:'登记未到访',change_approve:'批准变更',change_reject:'拒绝变更',followup:'登记跟进',reject:'无法接待',close:'结束咨询'}[l.action] || '业务操作')}</p>)}</section></Drawer>;
}
export function Slots() {
  const remote=useRemote('slots'), packages=useRemote('packages');
  const [editing,setEditing]=useState(null);
  return <>
    <div className="note-box"><h3>接待场次与研学报名</h3><p>普通场次用于预约接待安排。已成团的场次可填写活动信息并发布，游客从小程序“研学 → 研学报名”选择活动申请跟团。系统外已成团人数与系统已确认人数共同计入人数上限；待确认申请不占名额，工作人员确认时重新检查容量。</p></div>
    <div className="toolbar"><p>先维护日期、时段、套餐和实际人数，再发布跟团报名活动。</p><button onClick={()=>setEditing({date:'',start:'',end:'',capacity:'',external_count:0,package_ids:[],paused:false,note:'',enrollment:{state:'draft',title:'',packageId:'',description:'',meetingPoint:'',feeNote:'',registrationNote:''}})}>新增场次</button><button className="secondary" onClick={remote.refresh}>刷新</button></div>
    <ErrorBox error={remote.error}/><Loading loading={remote.loading}/><div className="table-region"><table className="slots-table"><thead><tr><th>日期 / 活动</th><th>时段</th><th>人数上限</th><th>系统外人数</th><th>系统已确认</th><th>剩余名额</th><th>跟团发布</th><th>接待状态</th><th>操作</th></tr></thead><tbody>{remote.data?.map(s=><tr key={s.id}><td>{s.date}<small>{s.enrollment.title || '未设置报名活动'}</small></td><td>{s.start}—{s.end}</td><td>{s.capacity}</td><td>{s.external_count}</td><td>{s.confirmed_count}</td><td>{s.remaining}</td><td><span className={`status ${s.enrollment.state}`}>{{draft:'未发布',published:'已发布',archived:'已下架'}[s.enrollment.state]}</span></td><td>{s.paused?'已暂停':s.remaining>0?'可申请':'已满员'}</td><td><button className="text-button" onClick={()=>setEditing(s)}>编辑 / 发布</button></td></tr>)}</tbody></table>{!remote.loading && !remote.data?.length?<Empty>尚未配置场次，可先创建接待安排</Empty>:null}</div>
    {editing?<SlotEditor key={editing.id || 'new'} value={editing} packages={packages.data || []} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);remote.refresh();}}/>:null}
  </>;
}
function SlotEditor({value,packages,onClose,onSaved}) {
  const [form,setForm]=useState({...value,enrollment:{state:'draft',...value.enrollment}}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const change=(key,val)=>setForm(f=>({...f,[key]:val}));
  const changeActivity=(key,val)=>setForm(f=>({...f,enrollment:{...f.enrollment,[key]:val}}));
  const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const data={...form,capacity:Number(form.capacity),externalCount:Number(form.external_count),packageIds:form.package_ids};await (form.id?api(`slots/${form.id}`,{method:'PUT',body:JSON.stringify(data)}):post('slots',data));onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const eligible=packages.filter(p=>form.package_ids.includes(p.id));
  const occupied=Number(form.external_count)+(value.confirmed_count || 0);
  return <Drawer title="场次与研学报名配置" onClose={onClose} closeDisabled={busy}><form onSubmit={save}>
    <ErrorBox error={error}/><Field label="接待日期"><input type="date" required value={form.date} onInput={e=>change('date',e.currentTarget.value)} onChange={e=>change('date',e.target.value)}/></Field><div className="pair"><Field label="开始时间"><input type="time" required value={form.start} onInput={e=>change('start',e.currentTarget.value)} onChange={e=>change('start',e.target.value)}/></Field><Field label="结束时间"><input type="time" required value={form.end} onInput={e=>change('end',e.currentTarget.value)} onChange={e=>change('end',e.target.value)}/></Field></div>
    <Field label="场次总人数上限" hint="包含已成团人员及新增跟团人员；成人和儿童均计入人数。"><input type="number" min="1" max="10000" required value={form.capacity} onChange={e=>change('capacity',e.target.value)}/></Field>
    <Field label="系统外已成团人数" hint="仅填写未通过本系统确认的实际人数；已录入系统并确认的人员不要重复计数，没有则填0。"><input type="number" min="0" max="10000" required value={form.external_count} onChange={e=>change('external_count',e.target.value)}/></Field>
    <p className="muted">系统已确认 {value.confirmed_count || 0} 人；合计已占用 {occupied} 人；剩余 {Math.max(0,Number(form.capacity)-occupied)} 人。待确认申请不计入已占用人数。</p>
    <fieldset><legend>适用套餐</legend>{packages.map(p=><label className="check-row" key={p.id}><input type="checkbox" checked={form.package_ids.includes(p.id)} onChange={e=>setForm(f=>({...f,package_ids:e.target.checked?[...f.package_ids,p.id]:f.package_ids.filter(id=>id!==p.id),enrollment:!e.target.checked && f.enrollment.packageId===p.id?{...f.enrollment,packageId:''}:f.enrollment}))}/>{p.name}</label>)}</fieldset>
    <Field label="内部接待说明" hint="仅供工作人员查看；游客看到下方填写的活动与报名说明。"><textarea maxLength={1500} value={form.note} onChange={e=>change('note',e.target.value)}/></Field>
    <fieldset><legend>研学报名发布</legend>
      <Field label="报名发布状态"><select value={form.enrollment.state} onChange={e=>changeActivity('state',e.target.value)}><option value="draft">未发布</option><option value="published">发布到小程序研学报名</option><option value="archived">下架报名活动</option></select></Field>
      <Field label="活动名称"><input maxLength={120} required={form.enrollment.state==='published'} value={form.enrollment.title || ''} onChange={e=>changeActivity('title',e.target.value)}/></Field>
      <Field label="跟团套餐" hint="从本场次适用套餐中选择一个已发布套餐，游客报名时自动带入。"><select required={form.enrollment.state==='published'} value={form.enrollment.packageId || ''} onChange={e=>changeActivity('packageId',e.target.value)}><option value="">请选择套餐</option>{eligible.map(p=><option key={p.id} value={p.id} disabled={p.state!=='published'}>{p.name}{p.state!=='published'?'（未发布）':''}</option>)}</select></Field>
      <Field label="活动介绍" hint="展示给游客；留空时沿用套餐介绍。"><textarea maxLength={5000} value={form.enrollment.description || ''} onChange={e=>changeActivity('description',e.target.value)}/></Field>
      <Field label="集合地点"><input maxLength={300} required={form.enrollment.state==='published'} value={form.enrollment.meetingPoint || ''} onChange={e=>changeActivity('meetingPoint',e.target.value)}/></Field>
      <Field label="公开费用说明" hint="填写已核实说明；留空显示咨询工作人员，不自动计算费用或优惠。"><textarea maxLength={500} value={form.enrollment.feeNote || ''} onChange={e=>changeActivity('feeNote',e.target.value)}/></Field>
      <Field label="公开报名说明"><textarea maxLength={1500} value={form.enrollment.registrationNote || ''} onChange={e=>changeActivity('registrationNote',e.target.value)}/></Field>
      <small>发布的是已经成团的活动。报名提交后仍待人工确认；下架停止新增跟团申请，已有报名记录保留。若修改已有报名的日期或套餐，请建立新场次。</small>
    </fieldset>
    <label className="check-row"><input type="checkbox" checked={!!form.paused} onChange={e=>change('paused',e.target.checked)}/>暂停此场次申请及新确认</label>
    <button className="full" disabled={busy}>{busy?'保存中…':form.enrollment.state==='published'?'保存并发布':'保存场次'}</button>
  </form></Drawer>;
}
