import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync,mkdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {buildPlan,stableId,hash} from '../scripts/business-migration/plan.mjs';import {executionSql} from '../scripts/business-migration/sql.mjs';
const time='2026-10-09T00:00:00.000Z',identity={host:'127.0.0.1/32',port:55433,database:'hq_development',schema:'app'};
const record=(id,data,kind='product')=>({id,kind,name:id,data:{isTest:true,...data},state:'published',sort:1,version:2,created_at:time,updated_at:time});
function fixture(content,media=[]){return {source:{identity,content,media,skus:[]},target:{database:'postgres-i56vqlwu',content:[],media:[],skus:[]},evidence:{database:'postgres-i56vqlwu',objects:[],protected:['accounts','sessions','audit','idempotency','migrations','visitors','bookings','changes','consultations','slots'].map(table_name=>({table_name,table_hash:hash(''),rows:[],row_count:0}))},guide:{records:[],media:[]}};}
const plan=f=>buildPlan(f.source,f.target,f.evidence,f.guide,{root:process.cwd(),uploadDir:'/tmp/hq-approved-test'});
test('explicit size mapping preserves order, no guessed color or price',()=>{const p=plan(fixture([record('violin',{category:'violin',priceMode:'inquiry',specs:[{name:'4/4'},{name:'1/2'}]})]));assert.equal(p.content[0].data.options.length,1);assert.deepEqual(p.content[0].data.options[0].values.map(v=>v.label),['4/4','1/2']);assert.equal(p.skus.length,2);assert.ok(p.skus.every(s=>s.reference_price===null&&s.images.length===0));assert.equal(p.content[0].data.specs,undefined);});
test('unmapped dimension and old description remain manual, no target rows',()=>{for(const specs of [[{name:'红色'}],[{name:'4/4',description:'3年自然风干欧洲木材'}],[{name:'4/4'},{name:'4/4'}]]){const p=plan(fixture([record('violin',{category:'violin',specs})]));assert.equal(p.manualReview.length,1);assert.equal(p.content.length,0);}});
test('default gift creates one simple SKU without manufacturing options',()=>{const p=plan(fixture([record('gift',{category:'gift',price:24,specs:[{name:'默认规格',description:''}]})]));assert.equal(p.skus.length,1);assert.equal(p.content[0].data.variantMode,'simple');assert.deepEqual(p.content[0].data.options,[]);assert.equal(p.content[0].data.price,24);});
test('teaching content and all video files excluded; business video is conflict',()=>{const m={id:'video',mime:'video/mp4',filename:'test.mp4',sha256:hash('v'),size:1};const p=plan(fixture([record('lesson',{type:'video',mediaId:'video'},'lesson'),record('site',{mediaId:'video'},'site')],[m]));assert.equal(p.skippedVideo.length,1);assert.equal(p.skippedVideoFiles.length,1);assert.equal(p.conflicts.length,1);assert.equal(p.media.length,0);assert.throws(()=>executionSql(p));});
test('same business name is a conflict; specifically resolved package stays pending',()=>{const f=fixture([record('x',{},'package'),record('package-1',{},'package')]);f.target.content=[record('other',{},'package')];f.target.content[0].name='x';const p=plan(f);assert.equal(p.conflicts.length,1);assert.equal(p.manualReview.length,1);assert.equal(p.content.length,0);});
test('deterministic target IDs use current UUID v4 syntax',()=>{assert.equal(stableId('x'),stableId('x'));assert.notEqual(stableId('x'),stableId('y'));assert.match(stableId('x'),/^[0-9a-f-]{14}4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);});
test('only approved local source and known Staging database accepted',()=>{const f=fixture([]);f.source.identity={...identity,host:'172.17.0.13'};assert.throws(()=>plan(f),/SOURCE_NOT_LOCAL/);});
test('guide content alteration prevents planning',()=>{const f=fixture([record('spot',{},'spot')]);f.guide.records=[{source:{id:'spot'},targetId:'target'}];f.target.content=[record('target',{description:'changed'},'spot')];assert.throws(()=>plan(f),/GUIDE_CONTENT_CHANGED/);});
test('same image bytes deduplicate; system logo is never media',()=>{const dir=mkdtempSync(join(tmpdir(),'hq-plan-'));try{mkdirSync(join(dir,'.local/development-runtime/uploads'),{recursive:true});writeFileSync(join(dir,'.local/development-runtime/uploads/a.jpg'),Buffer.from([255,216,255,217]));const m={id:'a',mime:'image/jpeg',size:4,sha256:hash(Buffer.from([255,216,255,217])),object_key:'a.jpg',filename:'a.jpg'};const f=fixture([record('site',{images:['/assets/yorray-logo.png','/api/media/a']},'site')],[m]);f.target.media=[{...m,id:'target',object_key:'target.jpg',created_at:time}];f.evidence.objects=[{name:'target.jpg',metadata:{size:4,mimetype:'image/jpeg'}}];const p=buildPlan(f.source,f.target,f.evidence,f.guide,{root:dir,uploadDir:dir});assert.equal(p.media.length,1);assert.equal(p.media[0].action,'MEDIA_REUSE');assert.equal(p.content[0].data.images[0],'/assets/yorray-logo.png');}finally{rmSync(dir,{recursive:true,force:true});}});
test('system asset substitutions cannot inject an origin or replace business media',()=>{const f=fixture([record('site',{},'site')]);for(const systemAssetMappings of [{'/assets/yorray-logo.png':'https://example.com/logo.png'},{'/api/media/x':'/assets/yorray-logo-test.png'}])assert.throws(()=>buildPlan(f.source,f.target,f.evidence,f.guide,{root:process.cwd(),uploadDir:'/tmp/hq-approved-test',systemAssetMappings}),/INVALID_SYSTEM_ASSET_MAPPING/);});
test('SQL only inserts approved tables and guards all protected fingerprints',()=>{const p=plan(fixture([record('site',{intro:"' $phase2d$ ; arbitrary text"},'site')]));const sql=executionSql(p);assert.equal((sql.match(/INSERT INTO app\./g)||[]).length,3);assert.doesNotMatch(sql,/\b(?:UPDATE|DELETE|CREATE|ALTER|DROP|GRANT)\b/);for(const t of p.protectedBefore)assert.ok(sql.includes('PROTECTED_AFTER_CHANGED:'+t.table_name));assert.match(sql,/intro.*'' \$phase2d\$/);assert.throws(()=>executionSql(p,{testDatabase:'postgres'}));});
