import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,existsSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {openDatabase} from '../server/db.mjs';import {Service} from '../server/service.mjs';import {seed} from '../server/seed.mjs';import {productPayload,option} from '../server/sku-seed.mjs';import {listMedia} from '../server/media.mjs';import {createAccount,issueSession} from '../server/security.mjs';import {createHttpServer} from '../server/http.mjs';import {auditActionLabel} from '../admin/src/audit-actions.mjs';import {retireDefinition,historicalDefinition,persistedDefinition} from '../admin/src/sku-delete.mjs';import {planSkus} from '../shared/sku-model.mjs';
const actor={id:'isolated-delete',roles:['admin']};
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'content-delete-')),db=openDatabase(join(dir,'isolated.sqlite')),service=new Service(db);seed(db);t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});return {db,dir,s:service};}
function create(s,kind='product',state='draft',extra={}){const payload=kind==='product'?productPayload('隔离删除产品',[option('尺寸',['4/4','3/4'])],extra):{kind,name:'隔离删除'+kind,data:{isTest:true,images:[],...extra}};payload.state=state;return s.saveContent(actor,payload);}
function state(s,p,value){const {id,kind,name,sort,version,skus,specs,state,...data}=s.content(p.id,false);return s.saveContent(actor,{kind,name,sort,version,state:value,data,...(skus?{skus:skus.filter(s=>s.current)}:{})},id);}
function visitor(db){const id=randomUUID();db.prepare('INSERT INTO visitors VALUES (?,NULL,?)').run(id,'now');return {id};}
function consultation(s,db,p){return s.createConsultation(visitor(db),{contentId:p.id,skuId:p.skus?.find(s=>s.current&&s.enabled)?.id,contactName:'合成访客',phone:'13800000000',message:'隔离测试',consent:true},randomUUID());}
function booking(s,db,p,extra={}){return s.createBooking(visitor(db),{packageId:p.id,date:'2099-11-01',contactName:'合成访客',phone:'13800000000',adults:1,children:0,consent:true,...extra},randomUUID());}
function slot(s,p,extra={}){return s.saveSlot(actor,{date:'2099-11-01',start:'09:00',end:'11:00',capacity:20,packageIds:[p.id],note:'隔离',enrollment:{state:'draft'},...extra});}
const rejects=(fn,code)=>assert.throws(fn,e=>e.code===code);
for(const [kind,category,stateName] of [['product','violin','draft'],['product','violin','archived'],['product','gift','draft'],['package',null,'draft'],['lesson',null,'draft']])test(`CD safe delete ${kind}/${category}/${stateName}, audit survives`,t=>{const {s,db}=fixture(t),p=create(s,kind,stateName,category?{category}:{});assert.equal(s.contentDeleteCheck(actor,p.id).allowed,true);assert.deepEqual(s.deleteContent(actor,p.id,p.version),{ok:true,id:p.id});assert.equal(db.prepare('SELECT count(*) n FROM content WHERE id=?').get(p.id).n,0);assert.equal(db.prepare('SELECT count(*) n FROM product_skus WHERE product_id=?').get(p.id).n,0);const log=db.prepare("SELECT * FROM audit WHERE action='content.delete' AND object=?").get(p.id);assert.deepEqual(JSON.parse(log.detail),{id:p.id,kind:p.kind,name:p.name,state:stateName});assert.equal(auditActionLabel(log.action),'删除内容');assert.ok(db.prepare("SELECT 1 FROM audit WHERE action='content.create' AND object=?").get(p.id));});
test('CD published, unsupported, missing and invalid version fail without deletion',t=>{const {s}=fixture(t),p=create(s,'product','published');rejects(()=>s.deleteContent(actor,p.id,p.version),'CONTENT_DELETE_REQUIRES_UNPUBLISHED');const spot=s.listContent({kind:'spot'},true)[0];const archived=state(s,spot,'archived');rejects(()=>s.deleteContent(actor,archived.id,archived.version),'CONTENT_DELETE_UNSUPPORTED');rejects(()=>s.deleteContent(actor,'missing',1),'CONTENT_NOT_FOUND');rejects(()=>s.deleteContent(actor,p.id,'1'),'INVALID_VERSION');});
test('CD consultation snapshot blocks product, gift, lesson and package including closed history',t=>{const {s,db}=fixture(t);for(const [kind,extra] of [['product',{}],['product',{category:'gift'}],['lesson',{}],['package',{}]]){let p=create(s,kind,'published',extra);const c=consultation(s,db,p);db.prepare("UPDATE consultations SET state='closed' WHERE id=?").run(c.id);p=state(s,p,'archived');const before=db.prepare('SELECT * FROM consultations WHERE id=?').get(c.id);const check=s.contentDeleteCheck(actor,p.id);assert.equal(check.references.consultations,1);rejects(()=>s.deleteContent(actor,p.id,p.version),'CONTENT_DELETE_REFERENCED');assert.deepEqual(db.prepare('SELECT * FROM consultations WHERE id=?').get(c.id),before);assert.ok(!JSON.stringify(check).includes('13800000000'));}});
test('CD package slots protects package_ids and enrollment.packageId independently',t=>{const {s,db}=fixture(t);let a=create(s,'package','published'),b=create(s,'package','published');const row=slot(s,a,{enrollment:{state:'draft',packageId:b.id}});for(let p of [a,b]){p=state(s,p,'archived');assert.equal(s.contentDeleteCheck(actor,p.id).references.sessions,1);rejects(()=>s.deleteContent(actor,p.id,p.version),'CONTENT_DELETE_REFERENCED');}assert.ok(db.prepare('SELECT 1 FROM slots WHERE id=?').get(row.id));});
test('CD booking protects direct snapshot and all indirect enrollment/slot paths',t=>{const {s,db}=fixture(t);let p=create(s,'package','published');const b=booking(s,db,p);db.prepare("UPDATE bookings SET state='cancelled' WHERE id=?").run(b.id);p=state(s,p,'archived');assert.equal(s.contentDeleteCheck(actor,p.id).references.bookings,1);rejects(()=>s.deleteContent(actor,p.id,p.version),'CONTENT_DELETE_REFERENCED');const sl=slot(s,p);for(const [request,slotId] of [[{enrollment:{packageId:p.id}},null],[{slotId:sl.id},null],[{enrollment:{id:sl.id}},null],[{},sl.id]]){db.prepare('UPDATE bookings SET snapshot=?,request=?,slot_id=? WHERE id=?').run('{}',JSON.stringify(request),slotId,b.id);assert.equal(s.contentDeleteCheck(actor,p.id).references.bookings,1);rejects(()=>s.deleteContent(actor,p.id,p.version),'CONTENT_DELETE_REFERENCED');}});
test('CD latest state, new references and stale version are checked after preflight',t=>{const {s,db}=fixture(t);let p=create(s);const check=s.contentDeleteCheck(actor,p.id);p=state(s,p,'published');rejects(()=>s.deleteContent(actor,p.id,check.version),'CONTENT_DELETE_REQUIRES_UNPUBLISHED');p=state(s,p,'archived');const stale=p.version;p=state(s,p,'draft');rejects(()=>s.deleteContent(actor,p.id,stale),'VERSION_CONFLICT');assert.equal(s.contentDeleteCheck(actor,p.id).allowed,true);p=state(s,p,'published');consultation(s,db,p);p=state(s,p,'archived');rejects(()=>s.deleteContent(actor,p.id,p.version),'CONTENT_DELETE_REFERENCED');let pkg=create(s,'package','draft');assert.equal(s.contentDeleteCheck(actor,pkg.id).allowed,true);slot(s,pkg);rejects(()=>s.deleteContent(actor,pkg.id,pkg.version),'CONTENT_DELETE_REFERENCED');let pending=create(s,'package','draft');assert.equal(s.contentDeleteCheck(actor,pending.id).allowed,true);pending=state(s,pending,'published');booking(s,db,pending);pending=state(s,pending,'archived');rejects(()=>s.deleteContent(actor,pending.id,pending.version),'CONTENT_DELETE_REFERENCED');});
test('CD audit failure rolls back both content and SKU deletion; schema unchanged',t=>{const {s,db}=fixture(t),p=create(s),schema=db.prepare("SELECT * FROM sqlite_master ORDER BY name").all(),rows=db.prepare('SELECT * FROM product_skus WHERE product_id=?').all(p.id);db.exec("CREATE TRIGGER fail_delete_audit BEFORE INSERT ON audit WHEN NEW.action='content.delete' BEGIN SELECT RAISE(ABORT,'isolated audit failure'); END");assert.throws(()=>s.deleteContent(actor,p.id,p.version));assert.equal(s.content(p.id,false).id,p.id);assert.deepEqual(db.prepare('SELECT * FROM product_skus WHERE product_id=?').all(p.id),rows);db.exec('DROP TRIGGER fail_delete_audit');assert.deepEqual(db.prepare('SELECT * FROM sqlite_master ORDER BY name').all(),schema);});
test('CD media records/files survive all content deletes and usedBy recomputes including SKU',t=>{const {s,db,dir}=fixture(t);const media=(mime)=>{const id=randomUUID();writeFileSync(join(dir,id),'isolated media bytes');db.prepare('INSERT INTO media VALUES (?,?,?,?,?,?,?,?,?)').run(id,'synthetic',mime,20,'hash',id,'isolated',1,'now');return id;};const img=media('image/png'),skuImage=media('image/png'),video=media('video/mp4'),url='/api/media/'+img;let a=create(s,'product','draft',{images:[url]}),b=create(s,'product','draft',{images:[url]}),pkg=create(s,'package','draft',{images:[url]}),lesson=create(s,'lesson','draft',{images:[url],type:'video',mediaId:video});db.prepare('UPDATE product_skus SET images=? WHERE product_id=?').run(JSON.stringify(['/api/media/'+skuImage]),a.id);assert.equal(listMedia(db).find(m=>m.id===skuImage).usedBy.length,1);assert.equal(listMedia(db).find(m=>m.id===img).usedBy.length,4);s.deleteContent(actor,a.id,a.version);assert.equal(listMedia(db).find(m=>m.id===skuImage).usedBy.length,0);assert.equal(listMedia(db).find(m=>m.id===img).usedBy.length,3);for(const p of [b,pkg,lesson])s.deleteContent(actor,p.id,p.version);assert.ok(listMedia(db).every(m=>m.usedBy.length===0));assert.equal(listMedia(db).length,3);assert.ok([img,skuImage,video].every(id=>existsSync(join(dir,id))));});
test('CD HTTP permission matrix and private-free error contracts',async t=>{const {s,db,dir}=fixture(t),{server}=createHttpServer({db,uploads:dir,root:new URL('../',import.meta.url).pathname});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;const tokens={};for(const role of ['admin','content','reception']){const a=createAccount(db,{username:'cd_'+role,password:randomUUID(),roles:[role]});tokens[role]=issueSession(db,a.id,'admin').token;}
 const call=(path,role,method='GET',body)=>fetch(base+'/api/admin/content/'+path,{method,headers:{'Content-Type':'application/json','X-HQ-Action':'1',...(tokens[role]?{Cookie:'hq_admin='+tokens[role]}:{})},...(body?{body:JSON.stringify(body)}:{})});
 for(const [role,status] of [['admin',200],['content',200],['reception',403],['anonymous',401]]){const p=create(s);assert.equal((await call(p.id+'/delete-check',role)).status,status);const r=await call(p.id,role,'DELETE',{version:p.version});assert.equal(r.status,status);}
 let p=create(s,'lesson','published');consultation(s,db,p);p=state(s,p,'archived');const r=await call(p.id,'admin','DELETE',{version:p.version}),json=await r.json();assert.equal(r.status,409);assert.equal(json.code,'CONTENT_DELETE_REFERENCED');assert.equal(json.references.consultations,1);assert.ok(!JSON.stringify(json).includes('13800000000'));assert.equal((await call('missing','admin','DELETE',{version:1})).status,404);
});
test('CD draft definitions remove physically; persisted definitions retire without mutation',()=>{const o=option('颜色',['自然色','棕色']),base=structuredClone([o]),extra=option('套装',['基础']);assert.equal(persistedDefinition(base,extra.id),false);assert.equal(retireDefinition([o,extra],base,extra.id).length,1);const added={id:randomUUID(),label:'新值',sort:3,enabled:true};const withNew=[{...o,values:[...o.values,added]}];assert.equal(retireDefinition(withNew,base,o.id,added.id)[0].values.length,2);const retired=retireDefinition([o],base,o.id,o.values[1].id);assert.equal(retired[0].values[1].enabled,false);assert.equal(base[0].values[1].enabled,true);assert.equal(retireDefinition([o],base,o.id)[0].enabled,false);});
test('CD same-name history recovery detects trim/case and retains old definition identity',()=>{const o=option('Color',['Natural','Brown']);o.values[1].enabled=false;const added={id:randomUUID(),label:' brown ',sort:2,enabled:true};o.values.push(added);assert.equal(historicalDefinition([o],o.id,added.id).id,o.values[1].id);const retired={...o,enabled:false},newO=option(' COLOR ',['x']);assert.equal(historicalDefinition([retired,newO],newO.id).id,retired.id);});
