import {api,Content,ensureIdentity,newKey,go,message,RequestError} from '../../lib/api';
import {Product,skuState} from '../../lib/product-sku';
Page({data:{id:'',item:null as Content|null,skuId:'',specLabel:'',canSubmit:true,skuNotice:'',source:'联系咨询',loading:true,error:'',submitError:'',busy:false,form:{contactName:'',phone:'',message:'',consent:false}},_key:newKey(),_fingerprint:'',
 onLoad(o:Record<string,string>){this._key=newKey();this._fingerprint='';this.setData({id:o.id||'',skuId:o.skuId||'',source:o.source?decodeURIComponent(o.source):'联系咨询'});this.load();},
 async load(recover=false){this.setData({loading:true,error:'',canSubmit:false});try{if(this.data.id){const item=await api<Content>('/api/public/content/'+this.data.id);if(item.kind==='product'){const p=item as Product;const chosen=p.skus.find(s=>s.id===this.data.skuId);const state=skuState(p,!recover&&chosen?chosen.optionValues:undefined);this.setData({item,skuId:state.selectedSkuId,specLabel:state.specLabel,canSubmit:state.canConsult,skuNotice:state.skuNotice||((recover||(!chosen&&p.variantMode==='options'))?'规格已更新，请确认当前规格后再次提交。':'')});}else this.setData({item,skuId:'',specLabel:'',canSubmit:true});}else this.setData({canSubmit:true});}catch(e){this.setData({error:message(e)});}finally{this.setData({loading:false});}},
 retry(){this.load();},input(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value});},consent(e:WechatMiniprogram.CustomEvent<{value:string[]}>){this.setData({'form.consent':e.detail.value.includes('agree')});},privacy(){go('/pages/about/index?section=privacy');},
 chooseSku(){go('/pages/product/index?id='+encodeURIComponent(this.data.id));},
 async submit(){if(this.data.busy||this.data.loading||!this.data.canSubmit)return;this.setData({busy:true,submitError:''});try{await ensureIdentity();const payload={...this.data.form,contentId:this.data.id||null,...(this.data.item?.kind==='product'?{skuId:this.data.skuId}:{}),source:this.data.source};const fp=JSON.stringify(payload);if(this._fingerprint&&fp!==this._fingerprint)this._key=newKey();this._fingerprint=fp;const r=await api<{id:string}>('/api/visitor/consultations',{method:'POST',data:payload,auth:true,key:this._key});wx.redirectTo({url:'/pages/record/index?kind=consultations&id='+r.id});}catch(e){if(e instanceof RequestError&&['SKU_UNAVAILABLE','SKU_NOT_FOUND','SKU_PRODUCT_MISMATCH','SKU_REQUIRED'].includes(e.code)){await this.load(true);this.setData({submitError:'该规格已更新，请重新选择并确认后提交。'});}else if(e instanceof RequestError&&e.code==='PRODUCT_UNAVAILABLE'){this.setData({canSubmit:false,submitError:'该产品已下架，暂不可咨询。'});}else this.setData({submitError:message(e)});}finally{this.setData({busy:false});}}
});
