-- PostgreSQL initial application schema. No SQLite data import.
CREATE TABLE content (
      id TEXT PRIMARY KEY NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL, data JSONB NOT NULL,
      state TEXT NOT NULL DEFAULT 'draft', sort INTEGER NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);

CREATE TABLE accounts (
      id TEXT PRIMARY KEY NOT NULL, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL,
      roles JSONB NOT NULL, can_export BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL);

CREATE TABLE visitors (id TEXT PRIMARY KEY NOT NULL, wechat_openid TEXT UNIQUE, created_at TIMESTAMPTZ NOT NULL);

CREATE TABLE sessions (token_hash TEXT PRIMARY KEY NOT NULL, owner TEXT NOT NULL, type TEXT NOT NULL,
      expires_at BIGINT NOT NULL);

CREATE TABLE slots (id TEXT PRIMARY KEY NOT NULL, date DATE NOT NULL, start TIME NOT NULL, "end" TIME NOT NULL,
      capacity INTEGER NOT NULL CHECK(capacity>0), package_ids JSONB NOT NULL, paused BOOLEAN NOT NULL DEFAULT FALSE,
      note TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, external_count INTEGER NOT NULL DEFAULT 0 CHECK(external_count>=0), enrollment JSONB NOT NULL DEFAULT '{"state":"draft"}');

CREATE TABLE bookings (id TEXT PRIMARY KEY NOT NULL, owner TEXT NOT NULL REFERENCES visitors(id),
      snapshot JSONB NOT NULL, request JSONB NOT NULL, confirmed JSON, state TEXT NOT NULL, slot_id TEXT REFERENCES slots(id),
      headcount INTEGER NOT NULL CHECK(headcount>0), assignee TEXT REFERENCES accounts(id),
      contact_log JSON NOT NULL DEFAULT '[]', public_note TEXT NOT NULL DEFAULT '', arrived_at TIMESTAMPTZ,
      version INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);

CREATE TABLE changes (id TEXT PRIMARY KEY NOT NULL, booking_id TEXT NOT NULL REFERENCES bookings(id),
      type TEXT NOT NULL, data JSON NOT NULL, state TEXT NOT NULL DEFAULT 'pending',
      result JSON, created_at TIMESTAMPTZ NOT NULL, handled_at TIMESTAMPTZ);

CREATE TABLE consultations (id TEXT PRIMARY KEY NOT NULL, owner TEXT NOT NULL REFERENCES visitors(id),
      snapshot JSONB NOT NULL, request JSON NOT NULL, state TEXT NOT NULL, assignee TEXT REFERENCES accounts(id),
      followups JSON NOT NULL DEFAULT '[]', public_note TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);

CREATE TABLE idempotency (owner TEXT NOT NULL, route TEXT NOT NULL, key TEXT NOT NULL,
      fingerprint TEXT NOT NULL, response JSON NOT NULL, PRIMARY KEY(owner,route,key));

CREATE TABLE media (id TEXT PRIMARY KEY NOT NULL, filename TEXT NOT NULL, mime TEXT NOT NULL,
      size BIGINT NOT NULL, sha256 TEXT NOT NULL, object_key TEXT NOT NULL, rights TEXT NOT NULL,
      duration DOUBLE PRECISION, created_at TIMESTAMPTZ NOT NULL);

CREATE TABLE audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor TEXT NOT NULL,
      action TEXT NOT NULL, object TEXT NOT NULL, detail JSON NOT NULL, created_at TIMESTAMPTZ NOT NULL);

CREATE TABLE product_skus (
    id TEXT PRIMARY KEY NOT NULL,
    product_id TEXT NOT NULL REFERENCES content(id),
    sku_code TEXT NOT NULL CHECK(sku_code=btrim(sku_code) AND sku_code COLLATE "C" ~ '^[A-Za-z0-9_-]{1,64}$' ),
    option_values JSONB NOT NULL CHECK(jsonb_typeof(option_values)='object'),
    combination_key TEXT NOT NULL,
    reference_price NUMERIC CHECK(reference_price IS NULL OR (reference_price>=0 AND reference_price<=10000000)),
    images JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(images)='array'),
    enabled BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL CHECK(sort_order BETWEEN 0 AND 10000),
    disable_reason TEXT NOT NULL DEFAULT '' CHECK(disable_reason IN ('','manual','structure')),
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE(product_id,combination_key));

CREATE INDEX audit_action_created_at_id ON audit(action,created_at DESC,id DESC);

CREATE INDEX audit_actor_created_at_id ON audit(actor,created_at DESC,id DESC);

CREATE INDEX audit_created_at_id ON audit(created_at DESC,id DESC);

CREATE INDEX bookings_owner ON bookings(owner);

CREATE INDEX bookings_slot ON bookings(slot_id,state);

CREATE UNIQUE INDEX changes_pending ON changes(booking_id) WHERE state='pending';

CREATE INDEX consultations_owner ON consultations(owner);

CREATE INDEX product_skus_product_id ON product_skus(product_id);

CREATE UNIQUE INDEX product_skus_code_ci ON product_skus (lower(sku_code COLLATE "C"));
